// Greek lang variables by Jacaranda Bill

tinyMCE.addToLang('',{
table_desc : '&Aring;������� ������',
table_insert_row_before_desc : '&Aring;������� ������� &aring;����',
table_insert_row_after_desc : '&Aring;������� ������� ����',
table_delete_row_desc : '&Auml;�����&ouml;� �������',
table_insert_col_before_desc : '&Aring;������� ������ �����&aring;��',
table_insert_col_after_desc : '&Aring;������� ������ &auml;&aring;���',
table_delete_col_desc : '&Auml;�����&ouml;� ������',
insert_table_title : '&Aring;�������/&Auml;������� ������',
insert_table_width : '������',
insert_table_height : '����',
insert_table_cols : '����&aring;�',
insert_table_rows : '�������',
insert_table_cellspacing : '&Auml;�������',
insert_table_cellpadding : '�������',
insert_table_border : '�&aring;��������',
insert_table_align : '��������',
insert_table_align_default : '������.',
insert_table_align_left : '�����&aring;��',
insert_table_align_right : '&Auml;&aring;���',
insert_table_align_middle : '��� ������',
insert_table_class : '�����',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
