// French lang variables by Laurent Dran
// Modifi� par Normand Lamoureux le 2005-11-12

tinyMCE.addToLang('table',{
general_tab : 'G�n�ral',
advanced_tab : 'Avanc�',
general_props : 'Propri�t�s g�n�rales',
advanced_props : 'Propri�t�s avanc�es',
desc : 'Ins�rer/Modifier un tableau',
row_before_desc : 'Ins�rer une rang�e avant',
row_after_desc : 'Ins�rer une rang�e apr�s',
delete_row_desc : 'Effacer la rang�e',
col_before_desc : 'Ins�rer une colonne avant',
col_after_desc : 'Ins�rer une colonne apr�s',
delete_col_desc : 'Effacer la colonne',
rowtype : 'Type de rang�e',
title : 'Gestionnaire de tableau',
width : 'Largeur',
height : 'Hauteur',
cols : 'Colonnes',
rows : 'Rang�es',
cellspacing : 'Entre les cellules',
cellpadding : 'Marges int�rieures',
border : 'Bordures',
align : 'Alignement horizontal',
align_default : 'Par d�fault',
align_left : '� gauche',
align_right : '� droite',
align_middle : 'Centr�',
row_title : 'Propri�t�s des rang�es',
cell_title : 'Propri�t�s des cellules',
cell_type : 'Type',
row_desc : 'Propri�t�s des rang�es',
cell_desc : 'Propri�t�s des cellules',
valign : 'Alignement vertical',
align_top : 'Haut',
align_bottom : 'Bas',
props_desc : 'Propri�t�s du tableau',
bordercolor : 'Couleur des bordures',
bgcolor : 'Couleur d\'arri�re-plan',
merge_cells_title : 'Fusionner les cellules',
split_cells_desc : 'Scinder les cellules',
merge_cells_desc : 'Fusionner les cellules',
cut_row_desc : '�liminer la rang�e',
copy_row_desc : 'Copier la rang�e',
paste_row_before_desc : 'Coller la rang�e avant',
paste_row_after_desc : 'Coller la rang�e apr�s',
id : 'Id',
style: 'Style en ligne',
langdir : 'Sens d\'�criture',
langcode : 'Code de langue',
mime : 'Type MIME de la cible',
ltr : 'Vers la droite',
rtl : 'Vers la gauche',
bgimage : 'Image d\'arri�re-plan',
summary : 'Descriptif',
td : "Donn�e",
th : "En-t�te",
cell_cell : 'Appliquer � la cellule',
cell_row : 'Appliquer � toute la rang�e',
cell_all : 'Appliquer � tout le tableau',
row_row : 'Appliquer � la rang�e',
row_odd : 'Appliquer aux rang�es pair',
row_even : 'Appliquer aux rang�es impair',
row_all : 'Appliquer � toutes les rang�es',
thead : 'En-t�te',
tbody : 'Corps',
tfoot : 'Pied',
del : 'Effacer le tableau',
scope : 'Attribut scope',
row : 'Rang�e',
col : 'Colonne',
rowgroup : 'Groupe de rang�es',
colgroup : 'Groupe de colonnes',
missing_scope: 'Les attributs scope rendraient votre tableau de donn�es plus\naccessible � certains groupes d\'utilisateurs.\n\n�tes-vous s�r de ne pas vouloir sp�cifier\nd\'attribut scope aux cellules d\'en-t�te ?\n\n',
cellprops_delta_width : 50
});
