// HE lang variables

tinyMCE.addToLang('table',{
general_tab : '����',
advanced_tab : '�����',
general_props : '�������� ������',
advanced_props : '�������� �������',
desc : '����� ���� ����',
row_before_desc : '���� ���� ����',
row_after_desc : '���� ���� ����',
delete_row_desc : '��� ����',
col_before_desc : '���� ��� ����',
col_after_desc : '���� ��� ����',
delete_col_desc : '��� ���',
rowtype : '���� ���� �� �����',
title : '����/��� ����',
width : '����',
height : '����',
cols : '�����',
rows : '�����',
cellspacing : '����� ��� ����',
cellpadding : '����� ����',
border : '����',
align : '����',
align_default : '����� ����',
align_left : '����',
align_right : '����',
align_middle : '����',
row_title : '������� ���� �����',
cell_title : '������� �� �����',
cell_type : '��� ��',
row_desc : '������� ���� �����',
cell_desc : '������� �� �����',
valign : '���� ����',
align_top : '�����',
align_bottom : '����',
props_desc : '������� ����',
bordercolor : '��� ����',
bgcolor : '��� ���',
merge_cells_title : '��� ���� �����',
split_cells_desc : '��� ���� �����',
merge_cells_desc : '��� ���� �����',
cut_row_desc : '���� ���� ������',
copy_row_desc : '���� ���� ������',
paste_row_before_desc : '���� ���� ����',
paste_row_after_desc : '���� ���� ����',
id : 'Id',
style: '�����',
langdir : '����� ���',
langcode : '��� ���',
mime : '��� MIME �� ����',
ltr : '���� �����',
rtl : '���� �����',
bgimage : '����� ���',
summary : '�����',
td : "����",
th : "�����",
cell_cell : '���� �� �����',
cell_row : '���� �� �� ����� �����',
cell_all : '���� �� �� ����� �����',
row_row : '���� ���� ������',
row_odd : '���� ����� ��-������ �����',
row_even : '���� ����� ������ �����',
row_all : '���� �� �� ������ �����',
thead : '����� �����',
tbody : '��� �����',
tfoot : '����� �����',
del : '��� ����',
scope : '����',
row : '����',
col : '���',
rowgroup : '����� �����',
colgroup : '����� �����',
missing_scope: '��� ��� ���� ������� ������ ���� ����� �� ���� ������ �� �����? ��� ����� ������, ���� �� ������� ���� ��������� ����� ����� �� ����� �� ����� ������� �����.'
});
