// HU lang variables

tinyMCE.addToLang('table',{
general_tab : '�ltal�nos',
advanced_tab : 'Halad�',
general_props : '�ltal�nos be�ll�t�sok',
advanced_props : 'Halad� be�ll�t�sok',
desc : '�j t�bl�zat besz�r�sa',
row_before_desc : 'Sor besz�r�sa el�',
row_after_desc : 'Sor besz�r�sa m�g�',
delete_row_desc : 'Sor t�rl�se',
col_before_desc : 'Oszlop besz�r�sa el�',
col_after_desc : 'Oszlop besz�r�sa m�g�',
delete_col_desc : 'Oszlop t�rl�se',
rowtype : 'Sor a t�bl�zatr�szben',
title : 'T�bl�zat besz�r�sa/m�dos�t�sa',
width : 'Hossz�s�g',
height : 'Sz�less�g',
cols : 'Oszlopok',
rows : 'Sorok',
cellspacing : 'Cellak�z',
cellpadding : 'Cellakit�lt�s',
border : 'Keret',
align : 'Elhelyezked�s',
align_default : 'alap�rtelmezett',
align_left : 'Bal',
align_right : 'Jobb',
align_middle : 'K�z�p',
row_title : 'T�bl�zat sor tulajdons�gai',
cell_title : 'T�bl�zat cella tulajdons�gai',
cell_type : 'Cella t�pus',
row_desc : 'T�bl�zat sor tulajdons�gai',
cell_desc : 'T�bl�zat cella tulajdons�gai',
valign : 'F�gg�leges elhelyezked�s',
align_top : 'Fel�l',
align_bottom : 'Alul',
props_desc : 'T�bl�zat tulajdons�gai',
bordercolor : 'Keret sz�n',
bgcolor : 'H�tt�r sz�n',
merge_cells_title : 'T�bla cell�inak egyes�t�se',
split_cells_desc : 'T�bla cell�inak feloszt�sa',
merge_cells_desc : 'T�bla cell�inak egyes�t�se',
cut_row_desc : 'T�bl�zat sor kiv�g�sa',
copy_row_desc : 'T�bl�zat sor m�sol�sa',
paste_row_before_desc : 'T�bl�zat sor beilleszt�se el�',
paste_row_after_desc : 'T�bl�zat sor beilleszt�se m�g�',
id : 'Azonod�t�',
style: 'St�lus',
langdir : 'Sz�vegpoz�ci�',
langcode : 'Sz�veg k�d',
mime : 'C�l MIME t�pus',
ltr : 'Balr�l jobbra',
rtl : 'Jobbr�l balra',
bgimage : 'H�tt�rk�p',
summary : '�sszefoglal�',
td : "Adat",
th : "Fejl�c",
cell_cell : 'Aktu�lis cella friss�t�se',
cell_row : 'Minden cella friss�t�se a sorban',
cell_all : 'Minden cella friss�t�se a t�bl�ban',
row_row : 'Aktu�lis sor friss�t�se',
row_odd : 'P�ratlan sorok friss�t�se a t�bl�ban',
row_even : 'p�ros sorok friss�t�se a t�bl�ban',
row_all : 'Minden sor friss�t�se a t�bl�ban',
thead : 'T�bl�zat fejl�c',
tbody : 'T�bl�zat test',
tfoot : 'T�l�zat l�bl�c',
del : 'T�bla t�rl�se',
scope : 'Scope',
row : 'Row',
col : 'Col',
rowgroup : 'Row Group',
colgroup : 'Col Group',
missing_scope: 'Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.'
});
