/**
 * pt_br lang variables
 * Brazilian Portuguese
 *
 * Authors :
 *           Marcio Barbosa (mpg) <mpg@mpg.com.br>
 * Last Updated : November 26, 2005
 * TinyMCE Version : 2.0RC4
 */
tinyMCE.addToLang('table',{
general_tab : 'Geral',
advanced_tab : 'Avan�ado',
general_props : 'Propriedades Gerais',
advanced_props : 'Propriedades Avan�adas',
desc : 'Inserir uma nova tabela',
row_before_desc : 'Inserir uma linha antes',
row_after_desc : 'Inserir uma linha depois',
delete_row_desc : 'Apagar linha',
col_before_desc : 'Inserir uma coluna antes',
col_after_desc : 'Inserir uma coluna depois',
delete_col_desc : 'Remover coluna',
rowtype : 'Linhas na tabela parcial',
title : 'Inserir/Modificar Tabela',
width : 'Largura',
height : 'Altura',
cols : 'Colunas',
rows : 'Linhas',
cellspacing : 'Espa�amento das c�lulas',
cellpadding : 'Margem interna',
border : 'Borda',
align : 'Alinhamento',
align_default : 'Padr�o',
align_left : 'Esquerda',
align_right : 'Direita',
align_middle : 'Centrado',
row_title : 'Propriedades das linha',
cell_title : 'Propriedades da c�lula',
cell_type : 'Tipo de c�lula',
row_desc : 'Propriedades das linhas',
cell_desc : 'Propriedades da c�lula',
valign : 'Alinhamento vertical',
align_top : 'Superior',
align_bottom : 'Inferior',
props_desc : 'Propriedades da tabela',
bordercolor : 'C�r da borda',
bgcolor : 'C�r do fundo',
merge_cells_title : 'Juntar c�lulas',
merge_cells_desc : 'Juntar c�lulas da tabela',
split_cells_title : 'Separar c�lulas',
split_cells_desc : 'Separar c�lulas',
cut_row_desc : 'Apagar linha',
copy_row_desc : 'Copiar linha',
paste_row_before_desc : 'Colar linha antes',
paste_row_after_desc : 'Colar linha depois',
id : 'Id',
style: 'Estilo',
langdir : 'Dire��o do texto',
langcode : 'C�digo do idioma',
mime : 'Tipo de MIME do objeto',
ltr : 'Esquerda para direita',
rtl : 'Direita para esquerda',
bgimage : 'Imagem de fundo',
summary : 'Sum�rio',
td : "Dados",
th : "Cabe�alho",
cell_cell : 'Atulizar c�lula atual',
cell_row : 'Atualizar todas as c�dulas na linha',
cell_all : 'Atualizar todas as c�dulas da tabela',
row_row : 'Atualizar linha atual',
row_odd : 'Atualizar linhas �mpares na tabela',
row_even : 'Atualizar linhas pares na tabela',
row_all : 'Atualizar todas as linhas na tabela',
thead : 'Cabe�alho da tabela',
tbody : 'Corpo da tabela',
tfoot : 'Rodap� da tabela',
del : 'Apagar tabela',
dir : 'Dire��o',
scope : 'Escopo',
row : 'Linha',
col : 'Coluna',
rowgroup : 'Grupo de linhas',
colgroup : 'Grupo de colunas',
missing_scope: 'Tem certeza que deseja continuar sem especificar um escopo para este c�lula de cabe�alho. Sem isso talvez seja dif�cil para alguns usu�rios especiais entender ou conte�do ou visualizar a tabela.'
});
