// UK lang variables

tinyMCE.addToLang('table',{
general_tab : 'Genel',
advanced_tab : 'Geli�mi�',
general_props : 'Genel �zellikler',
advanced_props : 'Geli�mi� �zellikler',
desc : 'Yeni tablo ekle',
row_before_desc : 'Sat�r ekle(�ncesinde)',
row_after_desc : 'Sat�r ekle(sonras�nda)',
delete_row_desc : 'Sat�r� sil',
col_before_desc : 'Kolon ekle(�ncesinde)',
col_after_desc : 'Kolon ekle(sonras�nda)',
delete_col_desc : 'Kolonu sil',
rowtype : 'Row in table part',
title : 'Tablo ekle/d�zenle',
width : 'Geni�lik',
height : 'Y�kseklik',
cols : 'Kolonlar',
rows : 'Sat�rlar',
cellspacing : 'H�cre bo�lu�u',
cellpadding : 'H�cre dol�usu',
border : 'S�n�r kal�nl�k',
align : 'Hizalama',
align_default : 'Varsay�lan',
align_left : 'Sol',
align_right : 'Sa�',
align_middle : 'Orta',
row_title : 'Tablo sat�r �zellikleri',
cell_title : 'Tablo h�cre �zellikleri',
cell_type : 'H�cre tipi',
row_desc : 'Tablo sat�r �zellikleri',
cell_desc : 'Tablo h�cre �zellikleri',
valign : 'D��ey hizalama',
align_top : '�st',
align_bottom : 'Alt',
props_desc : 'Tablo �zellikleri',
bordercolor : 'S�n�r rengi',
bgcolor : 'Arkaplan rengi',
merge_cells_title : 'Tablo h�crelerini birle�tir',
split_cells_desc : 'Tablo h�crelerini ay�r',
merge_cells_desc : 'Tablo h�crelerini birle�tir',
cut_row_desc : 'Tablo sat�r�n� kes',
copy_row_desc : 'Tablo sat�r�n� kopyala',
paste_row_before_desc : 'Tablo sat�r� yap��t�r(�nce)',
paste_row_after_desc : 'Tablo sat�r� yap��t�r(sonra)',
id : 'Id',
style: 'Stil',
langdir : 'Yaz�m y�n�',
langcode : 'Dil kodu',
mime : 'Hedef MIME tipi',
ltr : 'Soldan sa�a',
rtl : 'Sa�dan sola',
bgimage : 'Arkaplan resmi',
summary : '�zet',
td : "Veri",
th : "Ba�l�k",
cell_cell : 'H�creyi g�ncelle',
cell_row : 'Sat�rdaki t�m h�creleri g�ncelle',
cell_all : 'Tablodaki t�m h�creleri g�ncelle',
row_row : 'Sat�r� g�ncelle',
row_odd : 'Tablodaki s�ras� tek olan sat�rlar� g�ncelle',
row_even : 'Tablodaki s�ras� �ift olan sat�rlar� g�ncelle',
row_all : 'Tablodaki t�m sat�rlar� g�ncelle',
thead : 'Tablo ba�l���',
tbody : 'Tablo g�vdesi',
tfoot : 'Table alt�',
del : 'Tabloyu sil',
scope : 'Kapsam',
row : 'Sat�r',
col : 'Kolon',
rowgroup : 'Sat�r Gurubu',
colgroup : 'Kolon Gurubu',
missing_scope: 'Tablo ba�l�k h�clerlerinin kapsamlar�n� belirmeden devam etmek istedi�inize emin misiniz? E�er belirtmesseniz tablo g�r�n�m�nde problemler olabilir!'
});
