// TW lang variables contributed by Jim Kou

tinyMCE.addToLang('',{
insert_table_align : '���',
insert_table_align_default : '�з�',
insert_table_align_left : '����',
insert_table_align_middle : '�m��',
insert_table_align_right : '���k',
insert_table_border : '�ؽu',
insert_table_cellpadding : '�r&Aring;�P�x�s�涡��',
insert_table_cellspacing : '�x�s�涡��',
insert_table_class : '�˦�',
insert_table_cols : '��',
insert_table_height : '����',
insert_table_rows : '�C',
insert_table_title : '�����D',
insert_table_width : '�e��',
table_delete_col_desc : '�R���@���x�s��',
table_delete_row_desc : '�R���@�C�x�s��',
table_desc : '���',
table_insert_col_after_desc : '�s�W�@���x�s��(��)',
table_insert_col_before_desc : '�s�W�@���x�s��(�e)',
table_insert_row_after_desc : '�s�W�@�C�x�s��(��)',
table_insert_row_before_desc : '�s�W�@�C�x�s��(�e)',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
