// Simplified Chinese lang variables contributed by tom_cat (thomaswangyang@gmail.com)

tinyMCE.addToLang('table',{
general_tab : 'һ��',
advanced_tab : '�߼�',
general_props : 'һ������',
advanced_props : '�߼�����',
desc : '����һ���±�',
row_before_desc : '��ǰ����һ��',
row_after_desc : '������һ��',
delete_row_desc : 'ɾ����',
col_before_desc : '�������һ��',
col_after_desc : '���Ҳ���һ��',
delete_col_desc : 'ɾ����',
rowtype : '������',
title : '����/�޸� ��',
width : '��',
height : '��',
cols : '����',
rows : '����',
cellspacing : '��Ԫ��ռ�',
cellpadding : '��Ԫ�����',
border : '�߿�',
align : '����',
align_default : 'Ĭ��',
align_left : '����',
align_right : '����',
align_middle : '����',
row_title : '�б���',
cell_title : '��Ԫ�����',
cell_type : '��Ԫ������',
row_desc : '������',
cell_desc : '��Ԫ������',
valign : '��ֱ����',
align_top : '����',
align_bottom : '�׶�',
props_desc : '������',
bordercolor : '�߿���ɫ',
bgcolor : '������ɫ',
merge_cells_title : '�ϲ����е�Ԫ�����',
split_cells_desc : '������е�Ԫ������',
merge_cells_desc : '�ϲ����е�Ԫ������',
cut_row_desc : '������',
copy_row_desc : '������',
paste_row_before_desc : '��ǰճ��һ��',
paste_row_after_desc : '���ճ��һ��',
id : '��ʶ',
style: '��ʽ',
langdir : '��д����',
langcode : '���Ա���',
mime : 'Ŀ�� MIME ����',
ltr : '������',
rtl : '���ҵ���',
bgimage : '����ͼƬ',
summary : 'С��',
td : "���",
th : "ҳü",
cell_cell : '���µ�ǰ��Ԫ��',
cell_row : '�����������е�Ԫ��',
cell_all : '���±������е�Ԫ��',
row_row : '���µ�ǰ��',
row_odd : '����������',
row_even : '����ż����',
row_all : '���±���������',
thead : '��ͷ',
tbody : '����',
tfoot : '��β',
del : 'ɾ���',
scope : '����',
row : '��',
col : '��',
rowgroup : '�м���',
colgroup : '�м���',
missing_scope: '��ȷ��Ҫ��û�������༭����ʱ������û�������༭����ʹ�Ķ��߿������ܷ�����'
});
