// Traditional Chinese BIG-5; Twapweb Site translated; twapweb_AT_gmail_DOT_com
// �c�餤�� BIG-5 �F�Ʀ����Χ{�s�@�F twapweb_AT_gmail_DOT_com

tinyMCE.addToLang('table',{
general_tab : '�@��',
advanced_tab : '�i��',
general_props : '�@���ݩ�',
advanced_props : '�i���ݩ�',
desc : '���J�s���',
row_before_desc : '�b���e���J�C',
row_after_desc : '�b���ᴡ�J�C',
delete_row_desc : '�R���C',
col_before_desc : '�b���e���J��',
col_after_desc : '�b���ᴡ�J��',
delete_col_desc : '�R����',
rowtype : '��椤���C',
title : '���J�νվ���',
width : '�e',
height : '��',
cols : '��',
rows : '�C',
cellspacing : '�x�s���u���Z',
cellpadding : '�x�s�椺��P��u���Z',
border : '�ؽu',
align : '��m',
align_default : '���w',
align_left : '�a��',
align_right : '�a�k',
align_middle : '�m��',
row_title : '�C�ݩ�',
cell_title : '�x�s���ݩ�',
cell_type : '�x�s������',
row_desc : '�C�ݩ�',
cell_desc : '�x�s���ݩ�',
valign : '������m',
align_top : '����',
align_bottom : '����',
props_desc : '����ݩ�',
bordercolor : '�ؽu�C��',
bgcolor : '�I���C��',
merge_cells_title : '�X���x�s��',
split_cells_desc : '�����x�s��',
merge_cells_desc : '�X���x�s��',
cut_row_desc : '�ŤU�C',
copy_row_desc : '�ƻs�C',
paste_row_before_desc : '�b���e�K�W�C',
paste_row_after_desc : '�b����K�W�C',
id : '�s�X',
style: '����',
langdir : '�y���Ϊk',
langcode : '�y�X',
mime : '��H MIME ����',
ltr : '�ѥ��ܥk',
rtl : '�ѥk�ܥ�',
bgimage : '�I������',
summary : '�@��',
td : "���",
th : "���Y",
cell_cell : '��s�Ҧb���x�s��',
cell_row : '��s�C�����x�s��',
cell_all : '��s��椤���x�s��',
row_row : '��s�Ҧb���C',
row_odd : '��s��椤���_�ƦC',
row_even : '��s��椤�����ƦC',
row_all : '��s��椤���C',
thead : '�����Y',
tbody : '������',
tfoot : '��橳��',
del : '�R�����',
scope : '�d��',
row : '�C',
col : '��',
rowgroup : '�s�C',
colgroup : '�s��',
missing_scope: '�T�w�n�b�S���惡�����Y�]�w�d��U�~�����ܡH\n���[�H�]�w���ܡA�i��|�ɭP�Y�ǨϥΪ̵L�k���QŪ���椤�������άO�����T�C'
});
