<?xml version="1.0" encoding="UTF-8"?>

<!--
#################################################################################################
###
### uniBox 2.0 (winterspring)
### (c) Media Soma GbR
###
#################################################################################################
-->

<xsl:stylesheet version="1.0" xmlns="http://www.w3.org/1999/xhtml" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:php="http://php.net/xsl">
	<xsl:template name="form_color_picker">
		<xsl:variable name="theme_base" select="/root/unibox/theme_base[@template='main']/path" />

		<script src="{/root/unibox/html_base}{$theme_base}/scripts/form_colorpicker.js" type="text/javascript"></script>

		<xsl:param name="form_name" />
		<xsl:param name="field_name" />
		<img src="{$theme_base}/media/images/instanthelp_show.gif" id="toggle_color_picker_{field_name}" alt="{/root/translations/TRL_COLOR_PICKER_SHOW}" title="{/root/translations/TRL_COLOR_PICKER_SHOW}" class="color_picker" onclick="JavaScript: toggle_color_picker('{field_name}', '{$theme_base}', '{/root/translations/TRL_COLOR_PICKER_SHOW}', '{/root/translations/TRL_COLOR_PICKER_VANISH}');" />
		<div id="color_picker_{field_name}" class="form_color_picker">
			<a href="{/root/unibox/query_string}#color_picker_{$form_name}_{$field_name}" class="invisible"><xsl:value-of select="/root/translations/TRL_JUMP_OVER_COLOR_PICKER" /></a>
			<div class="form_color_picker_row">
				<div class="form_color_picker_column" title="#00FF00" style="background-color: #00FF00" onclick="javascript:set_color('{$form_name}', '{$field_name}', '00FF00')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '00FF00')" class="invisible">#00FF00</a></div>
				<div class="form_color_picker_column" title="#00FF33" style="background-color: #00FF33" onclick="javascript:set_color('{$form_name}', '{$field_name}', '00FF33')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '00FF33')" class="invisible">#00FF33</a></div>
				<div class="form_color_picker_column" title="#00FF66" style="background-color: #00FF66" onclick="javascript:set_color('{$form_name}', '{$field_name}', '00FF66')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '00FF66')" class="invisible">#00FF66</a></div>
				<div class="form_color_picker_column" title="#00FF99" style="background-color: #00FF99" onclick="javascript:set_color('{$form_name}', '{$field_name}', '00FF99')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '00FF99')" class="invisible">#00FF99</a></div>
				<div class="form_color_picker_column" title="#00FFCC" style="background-color: #00FFCC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '00FFCC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '00FFCC')" class="invisible">#00FFCC</a></div>
				<div class="form_color_picker_column" title="#00FFFF" style="background-color: #00FFFF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '00FFFF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '00FFFF')" class="invisible">#00FFFF</a></div>
				<div class="form_color_picker_column" title="#33FF00" style="background-color: #33FF00" onclick="javascript:set_color('{$form_name}', '{$field_name}', '33FF00')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '33FF00')" class="invisible">#33FF00</a></div>
				<div class="form_color_picker_column" title="#33FF33" style="background-color: #33FF33" onclick="javascript:set_color('{$form_name}', '{$field_name}', '33FF33')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '33FF33')" class="invisible">#33FF33</a></div>
				<div class="form_color_picker_column" title="#33FF66" style="background-color: #33FF66" onclick="javascript:set_color('{$form_name}', '{$field_name}', '33FF66')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '33FF66')" class="invisible">#33FF66</a></div>
				<div class="form_color_picker_column" title="#33FF99" style="background-color: #33FF99" onclick="javascript:set_color('{$form_name}', '{$field_name}', '33FF99')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '33FF99')" class="invisible">#33FF99</a></div>
				<div class="form_color_picker_column" title="#33FFCC" style="background-color: #33FFCC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '33FFCC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '33FFCC')" class="invisible">#33FFCC</a></div>
				<div class="form_color_picker_column" title="#33FFFF" style="background-color: #33FFFF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '33FFFF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '33FFFF')" class="invisible">#33FFFF</a></div>
				<div class="form_color_picker_column" title="#66FF00" style="background-color: #66FF00" onclick="javascript:set_color('{$form_name}', '{$field_name}', '66FF00')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '66FF00')" class="invisible">#66FF00</a></div>
				<div class="form_color_picker_column" title="#66FF33" style="background-color: #66FF33" onclick="javascript:set_color('{$form_name}', '{$field_name}', '66FF33')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '66FF33')" class="invisible">#66FF33</a></div>
				<div class="form_color_picker_column" title="#66FF66" style="background-color: #66FF66" onclick="javascript:set_color('{$form_name}', '{$field_name}', '66FF66')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '66FF66')" class="invisible">#66FF66</a></div>
				<div class="form_color_picker_column" title="#66FF99" style="background-color: #66FF99" onclick="javascript:set_color('{$form_name}', '{$field_name}', '66FF99')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '66FF99')" class="invisible">#66FF99</a></div>
				<div class="form_color_picker_column" title="#66FFCC" style="background-color: #66FFCC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '66FFCC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '66FFCC')" class="invisible">#66FFCC</a></div>
				<div class="form_color_picker_column" title="#66FFFF" style="background-color: #66FFFF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '66FFFF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '66FFFF')" class="invisible">#66FFFF</a></div>
				<div class="form_color_picker_column" title="#99FF00" style="background-color: #99FF00" onclick="javascript:set_color('{$form_name}', '{$field_name}', '99FF00')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '99FF00')" class="invisible">#99FF00</a></div>
				<div class="form_color_picker_column" title="#99FF33" style="background-color: #99FF33" onclick="javascript:set_color('{$form_name}', '{$field_name}', '99FF33')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '99FF33')" class="invisible">#99FF33</a></div>
				<div class="form_color_picker_column" title="#99FF66" style="background-color: #99FF66" onclick="javascript:set_color('{$form_name}', '{$field_name}', '99FF66')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '99FF66')" class="invisible">#99FF66</a></div>
				<div class="form_color_picker_column" title="#99FF99" style="background-color: #99FF99" onclick="javascript:set_color('{$form_name}', '{$field_name}', '99FF99')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '99FF99')" class="invisible">#99FF99</a></div>
				<div class="form_color_picker_column" title="#99FFCC" style="background-color: #99FFCC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '99FFCC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '99FFCC')" class="invisible">#99FFCC</a></div>
				<div class="form_color_picker_column" title="#99FFFF" style="background-color: #99FFFF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '99FFFF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '99FFFF')" class="invisible">#99FFFF</a></div>
				<div class="form_color_picker_column" title="#CCFF00" style="background-color: #CCFF00" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CCFF00')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CCFF00')" class="invisible">#CCFF00</a></div>
				<div class="form_color_picker_column" title="#CCFF33" style="background-color: #CCFF33" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CCFF33')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CCFF33')" class="invisible">#CCFF33</a></div>
				<div class="form_color_picker_column" title="#CCFF66" style="background-color: #CCFF66" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CCFF66')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CCFF66')" class="invisible">#CCFF66</a></div>
				<div class="form_color_picker_column" title="#CCFF99" style="background-color: #CCFF99" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CCFF99')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CCFF99')" class="invisible">#CCFF99</a></div>
				<div class="form_color_picker_column" title="#CCFFCC" style="background-color: #CCFFCC" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CCFFCC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CCFFCC')" class="invisible">#CCFFCC</a></div>
				<div class="form_color_picker_column" title="#CCFFFF" style="background-color: #CCFFFF" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CCFFFF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CCFFFF')" class="invisible">#CCFFFF</a></div>
				<div class="form_color_picker_column" title="#FFFF00" style="background-color: #FFFF00" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FFFF00')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FFFF00')" class="invisible">#FFFF00</a></div>
				<div class="form_color_picker_column" title="#FFFF33" style="background-color: #FFFF33" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FFFF33')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FFFF33')" class="invisible">#FFFF33</a></div>
				<div class="form_color_picker_column" title="#FFFF66" style="background-color: #FFFF66" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FFFF66')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FFFF66')" class="invisible">#FFFF66</a></div>
				<div class="form_color_picker_column" title="#FFFF99" style="background-color: #FFFF99" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FFFF99')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FFFF99')" class="invisible">#FFFF99</a></div>
				<div class="form_color_picker_column" title="#FFFFCC" style="background-color: #FFFFCC" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FFFFCC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FFFFCC')" class="invisible">#FFFFCC</a></div>
				<div class="form_color_picker_column" title="#FFFFFF" style="border-right: 1px solid #000000; background-color: #FFFFFF" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FFFFFF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FFFFFF')" class="invisible">#FFFFFF</a></div>
			</div>
			<div class="form_color_picker_row">
				<div class="form_color_picker_column" title="#00CC00" style="background-color: #00CC00" onclick="javascript:set_color('{$form_name}', '{$field_name}', '00CC00')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '00CC00')" class="invisible">#00CC00</a></div>
				<div class="form_color_picker_column" title="#00CC33" style="background-color: #00CC33" onclick="javascript:set_color('{$form_name}', '{$field_name}', '00CC33')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '00CC33')" class="invisible">#00CC33</a></div>
				<div class="form_color_picker_column" title="#00CC66" style="background-color: #00CC66" onclick="javascript:set_color('{$form_name}', '{$field_name}', '00CC66')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '00CC66')" class="invisible">#00CC66</a></div>
				<div class="form_color_picker_column" title="#00CC99" style="background-color: #00CC99" onclick="javascript:set_color('{$form_name}', '{$field_name}', '00CC99')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '00CC99')" class="invisible">#00CC99</a></div>
				<div class="form_color_picker_column" title="#00CCCC" style="background-color: #00CCCC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '00CCCC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '00CCCC')" class="invisible">#00CCCC</a></div>
				<div class="form_color_picker_column" title="#00CCFF" style="background-color: #00CCFF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '00CCFF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '00CCFF')" class="invisible">#00CCFF</a></div>
				<div class="form_color_picker_column" title="#33CC00" style="background-color: #33CC00" onclick="javascript:set_color('{$form_name}', '{$field_name}', '33CC00')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '33CC00')" class="invisible">#33CC00</a></div>
				<div class="form_color_picker_column" title="#33CC33" style="background-color: #33CC33" onclick="javascript:set_color('{$form_name}', '{$field_name}', '33CC33')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '33CC33')" class="invisible">#33CC33</a></div>
				<div class="form_color_picker_column" title="#33CC66" style="background-color: #33CC66" onclick="javascript:set_color('{$form_name}', '{$field_name}', '33CC66')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '33CC66')" class="invisible">#33CC66</a></div>
				<div class="form_color_picker_column" title="#33CC99" style="background-color: #33CC99" onclick="javascript:set_color('{$form_name}', '{$field_name}', '33CC99')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '33CC99')" class="invisible">#33CC99</a></div>
				<div class="form_color_picker_column" title="#33CCCC" style="background-color: #33CCCC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '33CCCC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '33CCCC')" class="invisible">#33CCCC</a></div>
				<div class="form_color_picker_column" title="#33CCFF" style="background-color: #33CCFF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '33CCFF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '33CCFF')" class="invisible">#33CCFF</a></div>
				<div class="form_color_picker_column" title="#66CC00" style="background-color: #66CC00" onclick="javascript:set_color('{$form_name}', '{$field_name}', '66CC00')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '66CC00')" class="invisible">#66CC00</a></div>
				<div class="form_color_picker_column" title="#66CC33" style="background-color: #66CC33" onclick="javascript:set_color('{$form_name}', '{$field_name}', '66CC33')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '66CC33')" class="invisible">#66CC33</a></div>
				<div class="form_color_picker_column" title="#66CC66" style="background-color: #66CC66" onclick="javascript:set_color('{$form_name}', '{$field_name}', '66CC66')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '66CC66')" class="invisible">#66CC66</a></div>
				<div class="form_color_picker_column" title="#66CC99" style="background-color: #66CC99" onclick="javascript:set_color('{$form_name}', '{$field_name}', '66CC99')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '66CC99')" class="invisible">#66CC99</a></div>
				<div class="form_color_picker_column" title="#66CCCC" style="background-color: #66CCCC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '66CCCC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '66CCCC')" class="invisible">#66CCCC</a></div>
				<div class="form_color_picker_column" title="#66CCFF" style="background-color: #66CCFF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '66CCFF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '66CCFF')" class="invisible">#66CCFF</a></div>
				<div class="form_color_picker_column" title="#99CC00" style="background-color: #99CC00" onclick="javascript:set_color('{$form_name}', '{$field_name}', '99CC00')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '99CC00')" class="invisible">#99CC00</a></div>
				<div class="form_color_picker_column" title="#99CC33" style="background-color: #99CC33" onclick="javascript:set_color('{$form_name}', '{$field_name}', '99CC33')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '99CC33')" class="invisible">#99CC33</a></div>
				<div class="form_color_picker_column" title="#99CC66" style="background-color: #99CC66" onclick="javascript:set_color('{$form_name}', '{$field_name}', '99CC66')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '99CC66')" class="invisible">#99CC66</a></div>
				<div class="form_color_picker_column" title="#99CC99" style="background-color: #99CC99" onclick="javascript:set_color('{$form_name}', '{$field_name}', '99CC99')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '99CC99')" class="invisible">#99CC99</a></div>
				<div class="form_color_picker_column" title="#99CCCC" style="background-color: #99CCCC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '99CCCC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '99CCCC')" class="invisible">#99CCCC</a></div>
				<div class="form_color_picker_column" title="#99CCFF" style="background-color: #99CCFF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '99CCFF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '99CCFF')" class="invisible">#99CCFF</a></div>
				<div class="form_color_picker_column" title="#CCCC00" style="background-color: #CCCC00" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CCCC00')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CCCC00')" class="invisible">#CCCC00</a></div>
				<div class="form_color_picker_column" title="#CCCC33" style="background-color: #CCCC33" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CCCC33')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CCCC33')" class="invisible">#CCCC33</a></div>
				<div class="form_color_picker_column" title="#CCCC66" style="background-color: #CCCC66" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CCCC66')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CCCC66')" class="invisible">#CCCC66</a></div>
				<div class="form_color_picker_column" title="#CCCC99" style="background-color: #CCCC99" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CCCC99')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CCCC99')" class="invisible">#CCCC99</a></div>
				<div class="form_color_picker_column" title="#CCCCCC" style="background-color: #CCCCCC" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CCCCCC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CCCCCC')" class="invisible">#CCCCCC</a></div>
				<div class="form_color_picker_column" title="#CCCCFF" style="background-color: #CCCCFF" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CCCCFF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CCCCFF')" class="invisible">#CCCCFF</a></div>
				<div class="form_color_picker_column" title="#FFCC00" style="background-color: #FFCC00" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FFCC00')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FFCC00')" class="invisible">#FFCC00</a></div>
				<div class="form_color_picker_column" title="#FFCC33" style="background-color: #FFCC33" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FFCC33')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FFCC33')" class="invisible">#FFCC33</a></div>
				<div class="form_color_picker_column" title="#FFCC66" style="background-color: #FFCC66" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FFCC66')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FFCC66')" class="invisible">#FFCC66</a></div>
				<div class="form_color_picker_column" title="#FFCC99" style="background-color: #FFCC99" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FFCC99')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FFCC99')" class="invisible">#FFCC99</a></div>
				<div class="form_color_picker_column" title="#FFCCCC" style="background-color: #FFCCCC" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FFCCCC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FFCCCC')" class="invisible">#FFCCCC</a></div>
				<div class="form_color_picker_column" title="#FFCCFF" style="border-right: 1px solid #000000; background-color: #FFCCFF" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FFCCFF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FFCCFF')" class="invisible">#FFCCFF</a></div>
			</div>
			<div class="form_color_picker_row">
				<div class="form_color_picker_column" title="#009900" style="background-color: #009900" onclick="javascript:set_color('{$form_name}', '{$field_name}', '009900')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '009900')" class="invisible">#009900</a></div>
				<div class="form_color_picker_column" title="#009933" style="background-color: #009933" onclick="javascript:set_color('{$form_name}', '{$field_name}', '009933')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '009933')" class="invisible">#009933</a></div>
				<div class="form_color_picker_column" title="#009966" style="background-color: #009966" onclick="javascript:set_color('{$form_name}', '{$field_name}', '009966')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '009966')" class="invisible">#009966</a></div>
				<div class="form_color_picker_column" title="#009999" style="background-color: #009999" onclick="javascript:set_color('{$form_name}', '{$field_name}', '009999')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '009999')" class="invisible">#009999</a></div>
				<div class="form_color_picker_column" title="#0099CC" style="background-color: #0099CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '0099CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '0099CC')" class="invisible">#0099CC</a></div>
				<div class="form_color_picker_column" title="#0099FF" style="background-color: #0099FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '0099FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '0099FF')" class="invisible">#0099FF</a></div>
				<div class="form_color_picker_column" title="#339900" style="background-color: #339900" onclick="javascript:set_color('{$form_name}', '{$field_name}', '339900')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '339900')" class="invisible">#339900</a></div>
				<div class="form_color_picker_column" title="#339933" style="background-color: #339933" onclick="javascript:set_color('{$form_name}', '{$field_name}', '339933')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '339933')" class="invisible">#339933</a></div>
				<div class="form_color_picker_column" title="#339966" style="background-color: #339966" onclick="javascript:set_color('{$form_name}', '{$field_name}', '339966')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '339966')" class="invisible">#339966</a></div>
				<div class="form_color_picker_column" title="#339999" style="background-color: #339999" onclick="javascript:set_color('{$form_name}', '{$field_name}', '339999')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '339999')" class="invisible">#339999</a></div>
				<div class="form_color_picker_column" title="#3399CC" style="background-color: #3399CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '3399CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '3399CC')" class="invisible">#3399CC</a></div>
				<div class="form_color_picker_column" title="#3399FF" style="background-color: #3399FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '3399FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '3399FF')" class="invisible">#3399FF</a></div>
				<div class="form_color_picker_column" title="#669900" style="background-color: #669900" onclick="javascript:set_color('{$form_name}', '{$field_name}', '669900')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '669900')" class="invisible">#669900</a></div>
				<div class="form_color_picker_column" title="#669933" style="background-color: #669933" onclick="javascript:set_color('{$form_name}', '{$field_name}', '669933')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '669933')" class="invisible">#669933</a></div>
				<div class="form_color_picker_column" title="#669966" style="background-color: #669966" onclick="javascript:set_color('{$form_name}', '{$field_name}', '669966')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '669966')" class="invisible">#669966</a></div>
				<div class="form_color_picker_column" title="#669999" style="background-color: #669999" onclick="javascript:set_color('{$form_name}', '{$field_name}', '669999')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '669999')" class="invisible">#669999</a></div>
				<div class="form_color_picker_column" title="#6699CC" style="background-color: #6699CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '6699CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '6699CC')" class="invisible">#6699CC</a></div>
				<div class="form_color_picker_column" title="#6699FF" style="background-color: #6699FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '6699FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '6699FF')" class="invisible">#6699FF</a></div>
				<div class="form_color_picker_column" title="#999900" style="background-color: #999900" onclick="javascript:set_color('{$form_name}', '{$field_name}', '999900')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '999900')" class="invisible">#999900</a></div>
				<div class="form_color_picker_column" title="#999933" style="background-color: #999933" onclick="javascript:set_color('{$form_name}', '{$field_name}', '999933')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '999933')" class="invisible">#999933</a></div>
				<div class="form_color_picker_column" title="#999966" style="background-color: #999966" onclick="javascript:set_color('{$form_name}', '{$field_name}', '999966')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '999966')" class="invisible">#999966</a></div>
				<div class="form_color_picker_column" title="#999999" style="background-color: #999999" onclick="javascript:set_color('{$form_name}', '{$field_name}', '999999')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '999999')" class="invisible">#999999</a></div>
				<div class="form_color_picker_column" title="#9999CC" style="background-color: #9999CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '9999CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '9999CC')" class="invisible">#9999CC</a></div>
				<div class="form_color_picker_column" title="#9999FF" style="background-color: #9999FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '9999FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '9999FF')" class="invisible">#9999FF</a></div>
				<div class="form_color_picker_column" title="#CC9900" style="background-color: #CC9900" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC9900')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC9900')" class="invisible">#CC9900</a></div>
				<div class="form_color_picker_column" title="#CC9933" style="background-color: #CC9933" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC9933')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC9933')" class="invisible">#CC9933</a></div>
				<div class="form_color_picker_column" title="#CC9966" style="background-color: #CC9966" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC9966')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC9966')" class="invisible">#CC9966</a></div>
				<div class="form_color_picker_column" title="#CC9999" style="background-color: #CC9999" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC9999')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC9999')" class="invisible">#CC9999</a></div>
				<div class="form_color_picker_column" title="#CC99CC" style="background-color: #CC99CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC99CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC99CC')" class="invisible">#CC99CC</a></div>
				<div class="form_color_picker_column" title="#CC99FF" style="background-color: #CC99FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC99FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC99FF')" class="invisible">#CC99FF</a></div>
				<div class="form_color_picker_column" title="#FF9900" style="background-color: #FF9900" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF9900')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF9900')" class="invisible">#FF9900</a></div>
				<div class="form_color_picker_column" title="#FF9933" style="background-color: #FF9933" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF9933')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF9933')" class="invisible">#FF9933</a></div>
				<div class="form_color_picker_column" title="#FF9966" style="background-color: #FF9966" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF9966')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF9966')" class="invisible">#FF9966</a></div>
				<div class="form_color_picker_column" title="#FF9999" style="background-color: #FF9999" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF9999')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF9999')" class="invisible">#FF9999</a></div>
				<div class="form_color_picker_column" title="#FF99CC" style="background-color: #FF99CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF99CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF99CC')" class="invisible">#FF99CC</a></div>
				<div class="form_color_picker_column" title="#FF99FF" style="border-right: 1px solid #000000; background-color: #FF99FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF99FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF99FF')" class="invisible">#FF99FF</a></div>
			</div>
			<div class="form_color_picker_row">
				<div class="form_color_picker_column" title="#006600" style="background-color: #006600" onclick="javascript:set_color('{$form_name}', '{$field_name}', '006600')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '006600')" class="invisible">#006600</a></div>
				<div class="form_color_picker_column" title="#006633" style="background-color: #006633" onclick="javascript:set_color('{$form_name}', '{$field_name}', '006633')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '006633')" class="invisible">#006633</a></div>
				<div class="form_color_picker_column" title="#006666" style="background-color: #006666" onclick="javascript:set_color('{$form_name}', '{$field_name}', '006666')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '006666')" class="invisible">#006666</a></div>
				<div class="form_color_picker_column" title="#006699" style="background-color: #006699" onclick="javascript:set_color('{$form_name}', '{$field_name}', '006699')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '006699')" class="invisible">#006699</a></div>
				<div class="form_color_picker_column" title="#0066CC" style="background-color: #0066CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '0066CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '0066CC')" class="invisible">#0066CC</a></div>
				<div class="form_color_picker_column" title="#0066FF" style="background-color: #0066FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '0066FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '0066FF')" class="invisible">#0066FF</a></div>
				<div class="form_color_picker_column" title="#336600" style="background-color: #336600" onclick="javascript:set_color('{$form_name}', '{$field_name}', '336600')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '336600')" class="invisible">#336600</a></div>
				<div class="form_color_picker_column" title="#336633" style="background-color: #336633" onclick="javascript:set_color('{$form_name}', '{$field_name}', '336633')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '336633')" class="invisible">#336633</a></div>
				<div class="form_color_picker_column" title="#336666" style="background-color: #336666" onclick="javascript:set_color('{$form_name}', '{$field_name}', '336666')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '336666')" class="invisible">#336666</a></div>
				<div class="form_color_picker_column" title="#336699" style="background-color: #336699" onclick="javascript:set_color('{$form_name}', '{$field_name}', '336699')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '336699')" class="invisible">#336699</a></div>
				<div class="form_color_picker_column" title="#3366CC" style="background-color: #3366CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '3366CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '3366CC')" class="invisible">#3366CC</a></div>
				<div class="form_color_picker_column" title="#3366FF" style="background-color: #3366FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '3366FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '3366FF')" class="invisible">#3366FF</a></div>
				<div class="form_color_picker_column" title="#666600" style="background-color: #666600" onclick="javascript:set_color('{$form_name}', '{$field_name}', '666600')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '666600')" class="invisible">#666600</a></div>
				<div class="form_color_picker_column" title="#666633" style="background-color: #666633" onclick="javascript:set_color('{$form_name}', '{$field_name}', '666633')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '666633')" class="invisible">#666633</a></div>
				<div class="form_color_picker_column" title="#666666" style="background-color: #666666" onclick="javascript:set_color('{$form_name}', '{$field_name}', '666666')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '666666')" class="invisible">#666666</a></div>
				<div class="form_color_picker_column" title="#666699" style="background-color: #666699" onclick="javascript:set_color('{$form_name}', '{$field_name}', '666699')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '666699')" class="invisible">#666699</a></div>
				<div class="form_color_picker_column" title="#6666CC" style="background-color: #6666CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '6666CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '6666CC')" class="invisible">#6666CC</a></div>
				<div class="form_color_picker_column" title="#6666FF" style="background-color: #6666FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '6666FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '6666FF')" class="invisible">#6666FF</a></div>
				<div class="form_color_picker_column" title="#996600" style="background-color: #996600" onclick="javascript:set_color('{$form_name}', '{$field_name}', '996600')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '996600')" class="invisible">#996600</a></div>
				<div class="form_color_picker_column" title="#996633" style="background-color: #996633" onclick="javascript:set_color('{$form_name}', '{$field_name}', '996633')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '996633')" class="invisible">#996633</a></div>
				<div class="form_color_picker_column" title="#996666" style="background-color: #996666" onclick="javascript:set_color('{$form_name}', '{$field_name}', '996666')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '996666')" class="invisible">#996666</a></div>
				<div class="form_color_picker_column" title="#996699" style="background-color: #996699" onclick="javascript:set_color('{$form_name}', '{$field_name}', '996699')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '996699')" class="invisible">#996699</a></div>
				<div class="form_color_picker_column" title="#9966CC" style="background-color: #9966CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '9966CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '9966CC')" class="invisible">#9966CC</a></div>
				<div class="form_color_picker_column" title="#9966FF" style="background-color: #9966FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '9966FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '9966FF')" class="invisible">#9966FF</a></div>
				<div class="form_color_picker_column" title="#CC6600" style="background-color: #CC6600" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC6600')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC6600')" class="invisible">#CC6600</a></div>
				<div class="form_color_picker_column" title="#CC6633" style="background-color: #CC6633" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC6633')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC6633')" class="invisible">#CC6633</a></div>
				<div class="form_color_picker_column" title="#CC6666" style="background-color: #CC6666" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC6666')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC6666')" class="invisible">#CC6666</a></div>
				<div class="form_color_picker_column" title="#CC6699" style="background-color: #CC6699" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC6699')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC6699')" class="invisible">#CC6699</a></div>
				<div class="form_color_picker_column" title="#CC66CC" style="background-color: #CC66CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC66CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC66CC')" class="invisible">#CC66CC</a></div>
				<div class="form_color_picker_column" title="#CC66FF" style="background-color: #CC66FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC66FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC66FF')" class="invisible">#CC66FF</a></div>
				<div class="form_color_picker_column" title="#FF6600" style="background-color: #FF6600" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF6600')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF6600')" class="invisible">#FF6600</a></div>
				<div class="form_color_picker_column" title="#FF6633" style="background-color: #FF6633" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF6633')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF6633')" class="invisible">#FF6633</a></div>
				<div class="form_color_picker_column" title="#FF6666" style="background-color: #FF6666" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF6666')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF6666')" class="invisible">#FF6666</a></div>
				<div class="form_color_picker_column" title="#FF6699" style="background-color: #FF6699" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF6699')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF6699')" class="invisible">#FF6699</a></div>
				<div class="form_color_picker_column" title="#FF66CC" style="background-color: #FF66CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF66CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF66CC')" class="invisible">#FF66CC</a></div>
				<div class="form_color_picker_column" title="#FF66FF" style="border-right: 1px solid #000000; background-color: #FF66FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF66FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF66FF')" class="invisible">#FF66FF</a></div>
			</div>
			<div class="form_color_picker_row">
				<div class="form_color_picker_column" title="#003300" style="background-color: #003300" onclick="javascript:set_color('{$form_name}', '{$field_name}', '003300')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '003300')" class="invisible">#003300</a></div>
				<div class="form_color_picker_column" title="#003333" style="background-color: #003333" onclick="javascript:set_color('{$form_name}', '{$field_name}', '003333')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '003333')" class="invisible">#003333</a></div>
				<div class="form_color_picker_column" title="#003366" style="background-color: #003366" onclick="javascript:set_color('{$form_name}', '{$field_name}', '003366')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '003366')" class="invisible">#003366</a></div>
				<div class="form_color_picker_column" title="#003399" style="background-color: #003399" onclick="javascript:set_color('{$form_name}', '{$field_name}', '003399')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '003399')" class="invisible">#003399</a></div>
				<div class="form_color_picker_column" title="#0033CC" style="background-color: #0033CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '0033CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '0033CC')" class="invisible">#0033CC</a></div>
				<div class="form_color_picker_column" title="#0033FF" style="background-color: #0033FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '0033FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '0033FF')" class="invisible">#0033FF</a></div>
				<div class="form_color_picker_column" title="#333300" style="background-color: #333300" onclick="javascript:set_color('{$form_name}', '{$field_name}', '333300')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '333300')" class="invisible">#333300</a></div>
				<div class="form_color_picker_column" title="#333333" style="background-color: #333333" onclick="javascript:set_color('{$form_name}', '{$field_name}', '333333')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '333333')" class="invisible">#333333</a></div>
				<div class="form_color_picker_column" title="#333366" style="background-color: #333366" onclick="javascript:set_color('{$form_name}', '{$field_name}', '333366')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '333366')" class="invisible">#333366</a></div>
				<div class="form_color_picker_column" title="#333399" style="background-color: #333399" onclick="javascript:set_color('{$form_name}', '{$field_name}', '333399')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '333399')" class="invisible">#333399</a></div>
				<div class="form_color_picker_column" title="#3333CC" style="background-color: #3333CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '3333CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '3333CC')" class="invisible">#3333CC</a></div>
				<div class="form_color_picker_column" title="#3333FF" style="background-color: #3333FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '3333FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '3333FF')" class="invisible">#3333FF</a></div>
				<div class="form_color_picker_column" title="#663300" style="background-color: #663300" onclick="javascript:set_color('{$form_name}', '{$field_name}', '663300')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '663300')" class="invisible">#663300</a></div>
				<div class="form_color_picker_column" title="#663333" style="background-color: #663333" onclick="javascript:set_color('{$form_name}', '{$field_name}', '663333')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '663333')" class="invisible">#663333</a></div>
				<div class="form_color_picker_column" title="#663366" style="background-color: #663366" onclick="javascript:set_color('{$form_name}', '{$field_name}', '663366')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '663366')" class="invisible">#663366</a></div>
				<div class="form_color_picker_column" title="#663399" style="background-color: #663399" onclick="javascript:set_color('{$form_name}', '{$field_name}', '663399')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '663399')" class="invisible">#663399</a></div>
				<div class="form_color_picker_column" title="#6633CC" style="background-color: #6633CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '6633CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '6633CC')" class="invisible">#6633CC</a></div>
				<div class="form_color_picker_column" title="#6633FF" style="background-color: #6633FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '6633FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '6633FF')" class="invisible">#6633FF</a></div>
				<div class="form_color_picker_column" title="#993300" style="background-color: #993300" onclick="javascript:set_color('{$form_name}', '{$field_name}', '993300')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '993300')" class="invisible">#993300</a></div>
				<div class="form_color_picker_column" title="#993333" style="background-color: #993333" onclick="javascript:set_color('{$form_name}', '{$field_name}', '993333')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '993333')" class="invisible">#993333</a></div>
				<div class="form_color_picker_column" title="#993366" style="background-color: #993366" onclick="javascript:set_color('{$form_name}', '{$field_name}', '993366')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '993366')" class="invisible">#993366</a></div>
				<div class="form_color_picker_column" title="#993399" style="background-color: #993399" onclick="javascript:set_color('{$form_name}', '{$field_name}', '993399')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '993399')" class="invisible">#993399</a></div>
				<div class="form_color_picker_column" title="#9933CC" style="background-color: #9933CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '9933CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '9933CC')" class="invisible">#9933CC</a></div>
				<div class="form_color_picker_column" title="#9933FF" style="background-color: #9933FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '9933FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '9933FF')" class="invisible">#9933FF</a></div>
				<div class="form_color_picker_column" title="#CC3300" style="background-color: #CC3300" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC3300')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC3300')" class="invisible">#CC3300</a></div>
				<div class="form_color_picker_column" title="#CC3333" style="background-color: #CC3333" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC3333')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC3333')" class="invisible">#CC3333</a></div>
				<div class="form_color_picker_column" title="#CC3366" style="background-color: #CC3366" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC3366')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC3366')" class="invisible">#CC3366</a></div>
				<div class="form_color_picker_column" title="#CC3399" style="background-color: #CC3399" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC3399')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC3399')" class="invisible">#CC3399</a></div>
				<div class="form_color_picker_column" title="#CC33CC" style="background-color: #CC33CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC33CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC33CC')" class="invisible">#CC33CC</a></div>
				<div class="form_color_picker_column" title="#CC33FF" style="background-color: #CC33FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC33FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC33FF')" class="invisible">#CC33FF</a></div>
				<div class="form_color_picker_column" title="#FF3300" style="background-color: #FF3300" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF3300')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF3300')" class="invisible">#FF3300</a></div>
				<div class="form_color_picker_column" title="#FF3333" style="background-color: #FF3333" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF3333')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF3333')" class="invisible">#FF3333</a></div>
				<div class="form_color_picker_column" title="#FF3366" style="background-color: #FF3366" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF3366')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF3366')" class="invisible">#FF3366</a></div>
				<div class="form_color_picker_column" title="#FF3399" style="background-color: #FF3399" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF3399')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF3399')" class="invisible">#FF3399</a></div>
				<div class="form_color_picker_column" title="#FF33CC" style="background-color: #FF33CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF33CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF33CC')" class="invisible">#FF33CC</a></div>
				<div class="form_color_picker_column" title="#FF33FF" style="border-right: 1px solid #000000; background-color: #FF33FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF33FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF33FF')" class="invisible">#FF33FF</a></div>
			</div>
			<div class="form_color_picker_row form_color_picker_row_last">
				<div class="form_color_picker_column" title="#000000" style="background-color: #000000" onclick="javascript:set_color('{$form_name}', '{$field_name}', '000000')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '000000')" class="invisible">#000000</a></div>
				<div class="form_color_picker_column" title="#000033" style="background-color: #000033" onclick="javascript:set_color('{$form_name}', '{$field_name}', '000033')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '000033')" class="invisible">#000033</a></div>
				<div class="form_color_picker_column" title="#000066" style="background-color: #000066" onclick="javascript:set_color('{$form_name}', '{$field_name}', '000066')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '000066')" class="invisible">#000066</a></div>
				<div class="form_color_picker_column" title="#000099" style="background-color: #000099" onclick="javascript:set_color('{$form_name}', '{$field_name}', '000099')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '000099')" class="invisible">#000099</a></div>
				<div class="form_color_picker_column" title="#0000CC" style="background-color: #0000CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '0000CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '0000CC')" class="invisible">#0000CC</a></div>
				<div class="form_color_picker_column" title="#0000FF" style="background-color: #0000FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '0000FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '0000FF')" class="invisible">#0000FF</a></div>
				<div class="form_color_picker_column" title="#330000" style="background-color: #330000" onclick="javascript:set_color('{$form_name}', '{$field_name}', '330000')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '330000')" class="invisible">#330000</a></div>
				<div class="form_color_picker_column" title="#330033" style="background-color: #330033" onclick="javascript:set_color('{$form_name}', '{$field_name}', '330033')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '330033')" class="invisible">#330033</a></div>
				<div class="form_color_picker_column" title="#330066" style="background-color: #330066" onclick="javascript:set_color('{$form_name}', '{$field_name}', '330066')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '330066')" class="invisible">#330066</a></div>
				<div class="form_color_picker_column" title="#330099" style="background-color: #330099" onclick="javascript:set_color('{$form_name}', '{$field_name}', '330099')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '330099')" class="invisible">#330099</a></div>
				<div class="form_color_picker_column" title="#3300CC" style="background-color: #3300CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '3300CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '3300CC')" class="invisible">#3300CC</a></div>
				<div class="form_color_picker_column" title="#3300FF" style="background-color: #3300FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '3300FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '3300FF')" class="invisible">#3300FF</a></div>
				<div class="form_color_picker_column" title="#660000" style="background-color: #660000" onclick="javascript:set_color('{$form_name}', '{$field_name}', '660000')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '660000')" class="invisible">#660000</a></div>
				<div class="form_color_picker_column" title="#660033" style="background-color: #660033" onclick="javascript:set_color('{$form_name}', '{$field_name}', '660033')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '660033')" class="invisible">#660033</a></div>
				<div class="form_color_picker_column" title="#660066" style="background-color: #660066" onclick="javascript:set_color('{$form_name}', '{$field_name}', '660066')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '660066')" class="invisible">#660066</a></div>
				<div class="form_color_picker_column" title="#660099" style="background-color: #660099" onclick="javascript:set_color('{$form_name}', '{$field_name}', '660099')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '660099')" class="invisible">#660099</a></div>
				<div class="form_color_picker_column" title="#6600CC" style="background-color: #6600CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '6600CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '6600CC')" class="invisible">#6600CC</a></div>
				<div class="form_color_picker_column" title="#6600FF" style="background-color: #6600FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '6600FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '6600FF')" class="invisible">#6600FF</a></div>
				<div class="form_color_picker_column" title="#990000" style="background-color: #990000" onclick="javascript:set_color('{$form_name}', '{$field_name}', '990000')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '990000')" class="invisible">#990000</a></div>
				<div class="form_color_picker_column" title="#990033" style="background-color: #990033" onclick="javascript:set_color('{$form_name}', '{$field_name}', '990033')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '990033')" class="invisible">#990033</a></div>
				<div class="form_color_picker_column" title="#990066" style="background-color: #990066" onclick="javascript:set_color('{$form_name}', '{$field_name}', '990066')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '990066')" class="invisible">#990066</a></div>
				<div class="form_color_picker_column" title="#990099" style="background-color: #990099" onclick="javascript:set_color('{$form_name}', '{$field_name}', '990099')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '990099')" class="invisible">#990099</a></div>
				<div class="form_color_picker_column" title="#9900CC" style="background-color: #9900CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', '9900CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '9900CC')" class="invisible">#9900CC</a></div>
				<div class="form_color_picker_column" title="#9900FF" style="background-color: #9900FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', '9900FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', '9900FF')" class="invisible">#9900FF</a></div>
				<div class="form_color_picker_column" title="#CC0000" style="background-color: #CC0000" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC0000')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC0000')" class="invisible">#CC0000</a></div>
				<div class="form_color_picker_column" title="#CC0033" style="background-color: #CC0033" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC0033')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC0033')" class="invisible">#CC0033</a></div>
				<div class="form_color_picker_column" title="#CC0066" style="background-color: #CC0066" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC0066')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC0066')" class="invisible">#CC0066</a></div>
				<div class="form_color_picker_column" title="#CC0099" style="background-color: #CC0099" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC0099')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC0099')" class="invisible">#CC0099</a></div>
				<div class="form_color_picker_column" title="#CC00CC" style="background-color: #CC00CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC00CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC00CC')" class="invisible">#CC00CC</a></div>
				<div class="form_color_picker_column" title="#CC00FF" style="background-color: #CC00FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'CC00FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'CC00FF')" class="invisible">#CC00FF</a></div>
				<div class="form_color_picker_column" title="#FF0000" style="background-color: #FF0000" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF0000')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF0000')" class="invisible">#FF0000</a></div>
				<div class="form_color_picker_column" title="#FF0033" style="background-color: #FF0033" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF0033')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF0033')" class="invisible">#FF0033</a></div>
				<div class="form_color_picker_column" title="#FF0066" style="background-color: #FF0066" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF0066')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF0066')" class="invisible">#FF0066</a></div>
				<div class="form_color_picker_column" title="#FF0099" style="background-color: #FF0099" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF0099')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF0099')" class="invisible">#FF0099</a></div>
				<div class="form_color_picker_column" title="#FF00CC" style="background-color: #FF00CC" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF00CC')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF00CC')" class="invisible">#FF00CC</a></div>
				<div class="form_color_picker_column" title="#FF00FF" style="border-right: 1px solid #000000; background-color: #FF00FF" onclick="javascript:set_color('{$form_name}', '{$field_name}', 'FF00FF')"><a href="JavaScript:javascript:set_color('{$form_name}', '{$field_name}', 'FF00FF')" class="invisible">#FF00FF</a></div>
			</div>
			<a name="color_picker_{$form_name}_{$field_name}" />
		</div>

		<script>
			<![CDATA[
				toggle_color_picker(']]><xsl:value-of select="field_name" /><![CDATA[', ']]><xsl:value-of select="$theme_base" /><![CDATA[', ']]><xsl:value-of select="/root/translations/TRL_COLOR_PICKER_SHOW" /><![CDATA[', ']]><xsl:value-of select="/root/translations/TRL_COLOR_PICKER_VANISH" /><![CDATA[')
			]]>
		</script>

	</xsl:template>
</xsl:stylesheet>