// Greek lang variables by Jacaranda Bill

tinyMCE.addToLang('',{
bold_desc : '������ ���&ouml;�',
italic_desc : '������ ���&ouml;�',
underline_desc : '�����������',
striketrough_desc : '&Auml;������� &auml;�����&ouml;�',
justifyleft_desc : '�������� �����&aring;��',
justifycenter_desc : '�������� ��� ������',
justifyright_desc : '�������� &auml;&aring;���',
justifyfull_desc : '������ ��������',
bullist_desc : '������&auml;&aring;�',
numlist_desc : '��������',
outdent_desc : '�&aring;���� &aring;�����',
indent_desc : '������ &aring;�����',
undo_desc : '�����&aring;��',
redo_desc : '������� �����&aring;���',
link_desc : '&Auml;���������/&Auml;������� ��&aring;�-���&auml;&aring;���',
unlink_desc : '&Auml;�����&ouml;� ��&aring;�-���&auml;&aring;���',
image_desc : '&Aring;�������/&Auml;������� &aring;������',
cleanup_desc : '��������� ��&auml;���',
focus_alert : '����&aring;� �� �����&aring;� &aring;�&aring;���� ������� &aring;�&aring;�&aring;������� �&aring;������ ���� �� ������������&aring;�&aring; ���� ��� &aring;�����.',
edit_confirm : '���&aring;�&aring; �� ������������&aring;�&aring; ��� ��������� WYSIWYG ��� �� ����&aring;������� ������� �&aring;������;',
insert_link_title : '&Auml;���������/&Auml;������� ��&aring;�-���&auml;&aring;���',
insert : '&Aring;�������',
update : '&Aring;�������',
cancel : '�������',
insert_link_url : '&Auml;�&aring;������',
insert_link_target : '������',
insert_link_target_same : '������� ��� &auml;�&aring;������� ��� �&auml;�� ��������',
insert_link_target_blank : '������� ��� &auml;�&aring;������� �&aring; ��� ��������',
insert_image_title : '&Aring;�������/&Auml;������� &aring;������',
insert_image_src : '&Auml;�&aring;������',
insert_image_alt : '�&aring;�����&ouml;�',
help_desc : '����&aring;��',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
