// FR lang variables by Pat Boens
// Modify by Laurent Dran
// Modifi� par Normand Lamoureux le 2005-11-12

tinyMCE.addToLang('',{
bold_desc : 'Gras',
italic_desc : 'Italique',
underline_desc : 'Soulign�',
striketrough_desc : 'Barr�',
justifyleft_desc : 'Aligner � gauche',
justifycenter_desc : 'Centrer',
justifyright_desc : 'Aligner � droite',
justifyfull_desc : 'Justifier',
bullist_desc : 'Liste � puces',
numlist_desc : 'Liste num�rot�e',
outdent_desc : 'Diminuer le retrait',
indent_desc : 'Augmenter le retrait',
undo_desc : 'Annuler',
redo_desc : 'Restaurer',
link_desc : 'Ins�rer/Modifier un lien',
unlink_desc : 'Supprimer le lien',
image_desc : 'Ins�rer/Modifier une image',
cleanup_desc : 'Nettoyer le code',
focus_alert : 'Une instance de l\�diteur doit avoir le focus avant d\'utiliser cette commande.',
edit_confirm : 'Voulez-vous utiliser le mode WYSIWYG pour cette zone d\'�dition de texte ?',
insert_link_title : 'Gestionnaire d\'hyperlien',
insert : 'Ins�rer',
update : 'Appliquer',
cancel : 'Annuler',
insert_link_url : 'Lien URL',
insert_link_target : 'Cible',
insert_link_target_same : 'Ouvrir dans la m�me fen�tre',
insert_link_target_blank : 'Ouvrir dans une nouvelle fen�tre',
insert_image_title : 'Gestionnaire d\'image',
insert_image_src : 'URL de l\'image',
insert_image_alt : '�quivalent textuel',
help_desc : 'Aide',
bold_img : "bold_fr.gif",
italic_img : "italic.gif",
underline_img : "underline_fr.gif",
clipboard_msg : 'Pour des raisons de s�curit�, les fonctions � Copier �, � Couper � et � Coller �\nne sont pas disponibles dans Mozilla et Firefox.\n\n\nVoulez-vous plus d\'information � ce sujet?\n',
popup_blocked : 'D�sol�, mais votre bloqueur de pop-up emp�che le fonctionnement normal de l\'application.\n\n\nPour utiliser cet outil, veuillez r�gler votre navigateur pour qu\'il accepte les pop-up de ce site.'
});
