// Canadian French lang variables by Virtuelcom

tinyMCE.addToLang('',{
bold_desc : 'Gras',
italic_desc : 'Italique',
underline_desc : 'Souligner',
striketrough_desc : 'Barrer',
justifyleft_desc : 'Aligner � gauche',
justifycenter_desc : 'Aligner au centre',
justifyright_desc : 'Aligner � droite',
justifyfull_desc : 'Justifier',
bullist_desc : 'Puces',
numlist_desc : 'Num�rotation',
outdent_desc : 'R�duire le retrait',
indent_desc : 'Augmenter le retrait',
undo_desc : 'Annuler la derni�re action',
redo_desc : 'Refaire la derni�re action annul�e',
link_desc : 'Ins�rer un hyperlien',
unlink_desc : 'Supprimer un hyperlien',
image_desc : 'Ins�rer une image',
cleanup_desc : 'Nettoyer le code',
focus_alert : 'Un �diteur doit �tre s�lectionn� pour utiliser cette fonction.',
edit_confirm : 'D�sirez-vous utiliser l\'�diteur pour modifier cette zone?',
insert_link_title : 'Ins�rer / Modifier un hyperlien',
insert : 'Ins�rer',
update : 'Ins�rer',
cancel : 'Annuler',
insert_link_url : 'Adresse URL',
insert_link_target : 'Destination',
insert_link_target_same : 'Ouvrir dans la m�me fen�tre',
insert_link_target_blank : 'Ouvrir dans une nouvelle fen�tre',
insert_image_title : 'Ins�rer / Modifier une image',
insert_image_src : 'Adresse de l\'image',
insert_image_alt : 'Description de l\'image',
help_desc : 'Aide',
bold_img : "bold_fr.gif",
italic_img : "italic.gif",
underline_img : "underline_fr.gif",
clipboard_msg : 'Copier/Couper/Coller ne sont pas disponibles dans Mozilla et FireFox.\nD�sirez-vous consulter de plus amples informations � ce sujet?'
});
