// HE lang variables by Liron Newman, http://eesh.net

tinyMCE.addToLang('',{
bold_desc : '����� (Ctrl+B)',
italic_desc : '���� (Ctrl+I)',
underline_desc : '�� ���� (Ctrl+U)',
striketrough_desc : '�� ����',
justifyleft_desc : '��� �����',
justifycenter_desc : '��� �����',
justifyright_desc : '��� �����',
justifyfull_desc : '��� ���� ������',
bullist_desc : '����� ���� ���',
numlist_desc : '����� ������',
outdent_desc : '���� �����',
indent_desc : '���� �����',
undo_desc : '��� (Ctrl+Z)',
redo_desc : '��� ��� (Ctrl+Y)',
link_desc : '����/���� �����',
unlink_desc : '��� �����',
image_desc : '����/���� �����',
cleanup_desc : '��� ��� ������',
focus_alert : '�� ����� ���� ����� ���� ����� ������ ������ ��.',
edit_confirm : '��� ������ ������ ���� ����� ����� (WYSIWYG) ���� ��� ���� ��?',
insert_link_title : '����/���� �����',
insert : '����',
update : '����',
cancel : '���',
insert_link_url : '����� (URL) ������',
insert_link_target : '���',
insert_link_target_same : '��� �� ������ ����� ����',
insert_link_target_blank : '��� �� ������ ����� ���',
insert_image_title : '����/���� �����',
insert_image_src : '����� (URL) ������',
insert_image_alt : '����� ������',
help_desc : '����',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : '������ �����/�����/����� ���� ������ ��� Mozilla �-Firefox.\n��� ������ ���� ���� ���� ����� ���� ��?',
popup_blocked : '�����, �� ���� �� �� ���� ������� ������� ��� ��� ���� ������ ��� �������. ����� ���� �� ����� ������� ������� ���� �� ��� ���� ��� �� ������.'
});
