// HU lang variables

tinyMCE.addToLang('',{
bold_desc : 'F�lk�v�r',
italic_desc : 'D�lt',
underline_desc : 'Al�h�zott',
striketrough_desc : '�th�zott',
justifyleft_desc : 'Balra igaz�tott',
justifycenter_desc : 'K�z�pre igaz�tott',
justifyright_desc : 'Jobbra igaz�tott',
justifyfull_desc : 'Telejesen igaz�tott',
bullist_desc : 'Rendezetlen lista',
numlist_desc : 'Rendezett lista',
outdent_desc : 'Kih�z�s',
indent_desc : 'Beh�z�s',
undo_desc : 'visszavon�s',
redo_desc : 'Ism�t',
link_desc : 'Link hozz�ad�sa/szerkeszt�se',
unlink_desc : 'Link megsz�ntet�se',
image_desc : 'K�p beilleszt�se/szerkeszt�se',
cleanup_desc : 'Rendetlen k�d tiszt�t�sa',
focus_alert : 'Egy szerkeszt�ablakra musz�j f�kusz�lni ennek a parancsnak a haszn�lata el�tt.',
edit_confirm : 'Szeretn�d haszn�lni ezt a WYSIWYG m�dot ehhez a sz�vegmez�h�z?',
insert_link_title : 'Link beilleszt�se/szerkeszt�se',
insert : 'Beilleszt�s',
update : 'Friss�t�s',
cancel : 'M�gse',
insert_link_url : 'Link URL',
insert_link_target : 'C�l',
insert_link_target_same : 'Link megnyit�sa ugyanabban az ablakban',
insert_link_target_blank : 'Link megnyit�sa �j ablakban',
insert_image_title : 'K�p beilleszt�se/szerkeszt�se',
insert_image_src : 'K�p URL',
insert_image_alt : 'K�p le�r�sa',
help_desc : 'S�g�',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'A M�sol�s/Kiv�g�s/Beilleszt�s nem el�rhet� Mozill�ban and Firefox-ban.\nSzeretn�l t�bb inform�ci�t err�l a probl�m�r�l?',
popup_blocked : 'Sajn�lom, de �szrevettem, hogy a popup-blokkol�d letiltotta az ablakot, ami biztos�tja ennek az alkalmaz�snak a m�k�d�s�t. Meg kell sz�ntetned a popup-blokkol�st ennek a seg�deszk�znek a teljes haszn�lat�hoz.'
});
