// Iceland lang variables by Johannes Birgir Jensson

tinyMCE.addToLang('',{
bold_desc : 'Feitletrun (Ctrl+B)',
italic_desc : 'Sk&aacute;letrun (Ctrl+I)',
underline_desc : 'Undirstrikun (Ctrl+U)',
striketrough_desc : 'Strik &iacute; gegn',
justifyleft_desc : 'Vinstri j&ouml;fnun',
justifycenter_desc : 'Mi&eth;ju j&ouml;fnun',
justifyright_desc : 'H&aelig;gri j&ouml;fnun',
justifyfull_desc : 'Samfelld j&ouml;fnun',
bullist_desc : '�ra&eth;a&eth;ur listi',
numlist_desc : 'Ra&eth;a&eth;ur listi',
outdent_desc : '�tdr&aacute;ttur',
indent_desc : 'Inndr&aacute;ttur',
undo_desc : 'Afturkalla (Ctrl+Z)',
redo_desc : 'Endurkalla (Ctrl+Y)',
link_desc : 'Setja inn/breyta hlekk',
unlink_desc : 'Fjarl&aelig;gja hlekk',
image_desc : 'Setja inn/breyta mynd',
cleanup_desc : 'Hreinsa ruslk&oacute;&eth;a',
focus_alert : 'Setja &thorn;arf bendil &iacute; ritsv&aelig;&eth;i &aacute;&eth;ur en &thorn;essi skipun er notu&eth;.',
edit_confirm : 'Viltu nota WYSIWYG &aacute; &thorn;essum reit?',
insert_link_title : 'N&yacute;r/breyttur hlekkur',
insert : 'Setja inn',
update : 'Uppf&aelig;ra',
cancel : 'H&aelig;tta vi&eth;',
insert_link_url : 'Sl&oacute;&eth; hlekks',
insert_link_target : 'Gluggi',
insert_link_target_same : 'Opna tengil &iacute; sama glugga',
insert_link_target_blank : 'Opna tengil &iacute; n&yacute;jum glugga',
insert_image_title : 'N&yacute;/breytt mynd',
insert_image_src : 'Sl&oacute;&eth; myndar',
insert_image_alt : 'L&yacute;sing myndar',
help_desc : 'Hj&aacute;lp',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Afrita/skeyta/l�ma er ekki leyft � vafranum.\nViltu f� frekari uppl�singar um hvernig � a� stilla �a�?',
popup_blocked : 'Afsaki�, gluggav�rn vafrans hefur meina� glugga, sem umsj�narkerfi� notar, leyfi til �ess a� opnast. �� ver�ur a� leyfa �essum vef a� opna sprettiglugga (popup) til a� geta n�tt �ennan m�guleika.'
});
