// KO lang variables by Setzer Gabbiani

tinyMCE.addToLang('',{
bold_desc : '���ϰ�',
italic_desc : '�����',
underline_desc : '����',
striketrough_desc : '������',
justifyleft_desc : '���� ���&Auml;',
justifycenter_desc : '��� ���&Auml;',
justifyright_desc : '������ ���&Auml;',
justifyfull_desc : '���� ���&Auml;',
bullist_desc : '���� �&Aring;���',
numlist_desc : '��ȣ �&Aring;���',
outdent_desc : '�����',
indent_desc : '�鿩����',
undo_desc : '�������',
redo_desc : '�����',
link_desc : '��&Aring;� �&Ouml;��/��&Auml;���',
unlink_desc : '��&Aring;� ����',
image_desc : '�׸� �&Ouml;��/��&Auml;���',
cleanup_desc : '&Auml;ڵ&aring;�� ����ϰ�',
focus_alert : '�� ����� �����ϱ� �� �ݵ&aring;�� ����&Aring;� ���� ��򰡿� &Auml;����� �&Ouml;��� �մϴ�.',
edit_confirm : '�� &Aring;ؽ�Ʈ �ڽ����� HTML ����&Aring;͸� ����ϱ� ���Ͻʴϱ�?',
insert_link_title : '��&Aring;� �&Ouml;��/��&Auml;���',
insert : '����',
update : '����',
cancel : '���',
insert_link_url : 'URL ��&Aring;�',
insert_link_target : '&Aring;���',
insert_link_target_same : '���� â���� ��&Aring;� ����',
insert_link_target_blank : '�� â���� ��&Aring;� ����',
insert_image_title : '�׸� �&Ouml;��/��&Auml;���',
insert_image_src : '�׸� URL',
insert_image_alt : '�׸� ����',
help_desc : '����',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
