// PT lang variables

tinyMCE.addToLang('',{
bold_desc : 'Negrito',
italic_desc : 'It�lico',
underline_desc : 'Sublinhar',
striketrough_desc : 'Riscado',
justifyleft_desc : 'Alinhar � esquerda',
justifycenter_desc : 'Alinhar ao centro',
justifyright_desc : 'Alinhar � direita',
justifyfull_desc : 'Justificado',
bullist_desc : 'Lista n�o ordenada',
numlist_desc : 'Lista ordenada',
outdent_desc : 'Retirar indenta��o',
indent_desc : 'Indentar',
undo_desc : 'Desfazer',
redo_desc : 'Refazer',
link_desc : 'Inserir Hiperliga��o',
unlink_desc : 'Remover hiperliga��o',
image_desc : 'Inserir Refer�ncia a imagem externa',
object_desc : 'Inserir Objecto Multim�dia da Galeria',
cleanup_desc : 'Limpeza de c�digo',
focus_alert : 'Uma inst�ncia do editor dever� estar seleccionada antes de utilizar este comando.',
edit_confirm : 'Deseja utilizar o modo visual de edi��o para ezta �rea de texto?',
insert_link_title : 'Inserir/editar hiperliga��o',
insert : 'Inserir',
update : 'Actualizar',
cancel : 'Cancelar',
insert_link_url : 'URL de hiperliga��o',
insert_link_target : 'Destino',
insert_link_target_same : 'Abrir endere�o na mesma janela',
insert_link_target_blank : 'Abrir endere�o numa nova janela',
insert_image_title : 'Inserir/editar imagem',
insert_image_src : 'Endere�o da imagem',
insert_image_alt : 'Descri��o alt.',
help_desc : 'Ajuda',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copiar/Cortar/Colar n�o est� dispon�vel em Mozilla and Firefox.\nPretende obter mais informa��o acerca desta quest�o?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
