// TH lang variables Thai contributed by Innozent

tinyMCE.addToLang('',{
bold_desc : '���˹�',
italic_desc : '�������§',
underline_desc : '�մ�����',
striketrough_desc : '�մ�&Aring;���',
justifyleft_desc : '�Դ�ͺ����',
justifycenter_desc : '�&Ouml;觡&Aring;ҧ',
justifyright_desc : '�Դ�ͺ���',
justifyfull_desc : '�Ѵ�Դ�ͺ',
bullist_desc : '�ѭ&Aring;ѡɳ��ʴ���Ǣ������',
numlist_desc : '&Aring;ӴѺ�&Aring;�',
outdent_desc : '&Aring;��������ͧ',
indent_desc : '�����������ͧ',
undo_desc : '�&Aring;ԡ��',
redo_desc : '������',
link_desc : '����&Aring;ԧ��',
unlink_desc : '&Aring;�&Aring;ԧ��',
image_desc : '����ٻ',
cleanup_desc : '�Ӥ������Ҵ��ͤ���',
focus_alert : '��ͧ�&Aring;�͡�&Aring;�ͧ��ͤ�����͹���������觹��',
edit_confirm : '�س��ͧ��÷����� WYSIWYG mode ����Ѻ�&Aring;�ͧ��ͤ����������&auml;��?',
insert_link_title : '����/��&auml;� &Aring;ԧ��',
insert : '����',
cancel : '¡�&Aring;ԡ',
insert_link_url : 'Link URL',
insert_link_target : '�Դ&Aring;ԧ���',
insert_link_target_same : '˹�ҵ�ҧ���ǡѹ',
insert_link_target_blank : '˹�ҵ�ҧ����',
insert_image_title : '����/��&auml;� �ٻ',
insert_image_src : 'URL �ͧ�ٻ',
insert_image_alt : '��͸Ժ���ٻ',
help_desc : '������&Aring;��',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
