// TR lang variables

tinyMCE.addToLang('',{
bold_desc : 'Kal�n (Ctrl+B)',
italic_desc : '�talik (Ctrl+I)',
underline_desc : 'Alt� �izgili (Ctrl+U)',
striketrough_desc : '�st� �izgili',
justifyleft_desc : 'Sola dayal�',
justifycenter_desc : 'Ortalanm��',
justifyright_desc : 'Sa�a dayal�',
justifyfull_desc : '�ki kenara yaslanm��',
bullist_desc : 'S�ras�z liste',
numlist_desc : 'S�ral� liste',
outdent_desc : 'Girintiyi azalt',
indent_desc : 'Girintiyi artt�r',
undo_desc : 'Geri al (Ctrl+Z)',
redo_desc : 'Yeniden yap (Ctrl+Y)',
link_desc : 'Link ekle/d�zenle',
unlink_desc : 'Linki kald�r',
image_desc : 'Resim ekle/d�zenle',
cleanup_desc : 'Da��n�k kodu d�zenle',
focus_alert : 'Bu komutu kullanmadan �nce edit�r se�ilmeli(aktif olmal�).',
edit_confirm : 'Bu text alan� i�in WYSIWYG modu kullanmak ister misiniz?',
insert_link_title : 'Link ekle/d�zenle',
insert : 'Ekle',
update : 'G�ncelle',
cancel : '�ptal',
insert_link_url : 'Link adresi giriniz',
insert_link_target : 'Hedef adres',
insert_link_target_same : 'Linki ayn� sayfada a�',
insert_link_target_blank : 'Linki yeni sayfada a�',
insert_image_title : 'Resim ekle/d�zenle',
insert_image_src : 'Resim adresi',
insert_image_alt : 'Resim a��klamas�',
help_desc : 'Yard�m',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Mozilla ve Firefox taray�c�lar�nda kopyala/kes/yap��t�r komutlar�n� kullanamass�n�z.\n Bu konu hakk�nda daha fazla bilgi edinmek ister misiniz?',
popup_blocked : 'Popup engelleyiciniz program�n �al��mas�n� �nlemektedir, bu �zellikten yararlanabilmeniz i�in popup engelleyicinizi kapatman�z gerekiyor.'
});