// Simplified Chinese lang variables contributed by tom_cat (thomaswangyang@gmail.com)

tinyMCE.addToLang('',{
bold_desc : '���� (Ctrl+B)',
italic_desc : 'б�� (Ctrl+I)',
underline_desc : '�»��� (Ctrl+U)',
striketrough_desc : 'ɾ����',
justifyleft_desc : '�����',
justifycenter_desc : '���ж���',
justifyright_desc : '�Ҷ���',
justifyfull_desc : '���˶���',
bullist_desc : '�����б�',
numlist_desc : '�����б�',
outdent_desc : '��������',
indent_desc : '��������',
undo_desc : '���� (Ctrl+Z)',
redo_desc : '���� (Ctrl+Y)',
link_desc : '����/�༭ ����',
unlink_desc : 'ɾ������',
image_desc : '����/�༭ ͼ��',
cleanup_desc : 'ɾ���������',
focus_alert : '����ѡ��༭��',
edit_confirm : '�����ڱ༭������ʹ�������ñ༭��ô��',
insert_link_title : '����/�༭ ����',
insert : '����',
update : '����',
cancel : 'ȡ��',
insert_link_url : '���ӵ�ַ',
insert_link_target : '����Ŀ��',
insert_link_target_same : '��ͬһ�����д�����',
insert_link_target_blank : '���´����д�����',
insert_image_title : '����/�༭ ͼ��',
insert_image_src : 'ͼ���ַ',
insert_image_alt : 'ͼ������',
help_desc : '����',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : '����/����/ճ������ Mozilla �� Firefox ������в�֧�֡���ϣ���ø�����Ϣ��',
popup_blocked : '�Բ���, ����������ֹ�˵���ʽ���ڡ�Ϊ������ʹ�õ������ƵĹ��ܣ���Ա���վ�ĵ���ʽ���ڽ���ֹ��'
});
