// Traditional Chinese BIG-5; Twapweb Site translated; twapweb_AT_gmail_DOT_com
// �c�餤�� BIG-5 �F�Ʀ����Χ{�s�@�F twapweb_AT_gmail_DOT_com

tinyMCE.addToLang('',{
bold_desc : '����]Ctrl+B�^',
italic_desc : '����]Ctrl+I�^',
underline_desc : '�[���u�]Ctrl+U�^',
striketrough_desc : '�R���u',
justifyleft_desc : '�a��',
justifycenter_desc : '�m��',
justifyright_desc : '�a�k',
justifyfull_desc : '��g���',
bullist_desc : '���ؤ覡��C',
numlist_desc : '�s���覡��C',
outdent_desc : '�X�j�Y��',
indent_desc : '��p�Y��',
undo_desc : '�_��]Ctrl+Z�^',
redo_desc : '���ơ]Ctrl+Y�^',
link_desc : '���J�νs��s��',
unlink_desc : '�R���s��',
image_desc : '���J�νs�����',
cleanup_desc : '�M�����X',
focus_alert : '�ϥΦ���O�e�����w�s�边',
edit_confirm : '�n�󦹤�r��J�Ϥ��ĥΩҵ�Y�o�Ҧ��ܡH',
insert_link_title : '���J�νs��s��',
insert : '���J',
update : '��s',
cancel : '���',
insert_link_url : '�s�����}',
insert_link_target : '��H',
insert_link_target_same : '��P���}�ҳs��',
insert_link_target_blank : '�H�s���}�ҳs��',
insert_image_title : '���J�νs�����',
insert_image_src : '���ɺ��}',
insert_image_alt : '���ɻ���',
help_desc : '��U',
bold_img : "bold_tw.gif",
italic_img : "italic_tw.gif",
underline_img : "underline_tw.gif",
clipboard_msg : '�b Mozilla �M Firefox ���L�k�ϥνƻs�ΰŤU�ζK�W�\��C\n�ݭn��h���󦹪��T���ܡH',
popup_blocked : '��I�z���]�m���{��j������A�w�N�\����{���j���F�C\n�нվ���{��j������]�w�A�~�ॿ�`�ϥΦ��\��C'
});