// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : '����',
popup_tab : '���� ����',
events_tab : '������',
advanced_tab : '�����',
general_props : '�������� ������',
popup_props : '������� ����� �����',
event_props : '������',
advanced_props : '�������� �������',
popup_opts : '��������',
anchor_names : '������',
target_same : '��� ����� �� �� ����� ��',
target_parent : '��� ����� �� ������ ��������',
target_top : '��� ������ ������ (����� �� �� �������)',
target_blank : '��� ����� ���',
popup : '���� ���� �� Javascript',
popup_url : '����� ����� �����',
popup_name : '�� �����',
popup_return : '���� \'return false\'',
popup_scrollbars : '��� ��� �����',
popup_statusbar : '��� ���� ���',
popup_toolbar : '��� ����� ����',
popup_menubar : '��� �� ���� ��������',
popup_location : '��� �� ���� ������',
popup_resizable : '���� ����� ����� �� �����',
popup_dependent : '���� (Mozilla/Firefox ����)',
popup_size : '����',
popup_position : '����� (X/Y)',
id : 'Id',
style: '�����',
classes : 'Class��',
target_name : '�� ���',
langdir : '����� ���',
target_langcode : '��� ���',
langcode : '��� ���',
encoding : '����� ����� �� ����',
mime : '��� MIME �� ����',
rel : '��� �� �� ����',
rev : '��� �� ��� ���',
tabindex : '��� �����',
accesskey : '��� ����',
ltr : '���� �����',
rtl : '���� �����'
});