// HU lang variables

tinyMCE.addToLang('advlink',{
general_tab : '�ltal�nos',
popup_tab : 'Popup',
events_tab : 'Esem�nyek',
advanced_tab : 'Halad�',
general_props : '�ltal�nos be�ll�t�sok',
popup_props : 'Popup be�ll�t�sok',
event_props : 'Esem�nyek',
advanced_props : 'Halad� be�ll�t�sok',
popup_opts : 'Opci�k',
anchor_names : 'Horgonyok',
target_same : 'Megnyit�s ebben az ablakban / keretben',
target_parent : 'Megnyit�s a sz�l� ablakban / keretben',
target_top : 'Megnyit�s fels� keretben (minden keretet lecser�l)',
target_blank : 'Megnyit�s �j ablakban',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Ablak n�v',
popup_return : '\'return false\' besz�r�sa',
popup_scrollbars : 'G�rget�s�vok megjelen�t�se',
popup_statusbar : '�llapotsor megjelen�t�se',
popup_toolbar : 'Eszk�zt�rak megjelen�t�se',
popup_menubar : 'Men�sor megjelen�t�se',
popup_location : 'C�ms�v megjelen�t�se',
popup_resizable : 'Ablak �tm�retezhet�v� t�tele',
popup_dependent : 'F�gg� (csak Mozilla/Firefox)',
popup_size : 'M�ret',
popup_position : 'Poz�ci� (X/Y)',
id : 'Azonos�t�',
style: 'St�lus',
classes : 'Oszt�lyok',
target_name : 'C�l neve',
langdir : 'Sz�veg poz�ci�',
target_langcode : 'C�l sz�veg',
langcode : 'Sz�veg k�d',
encoding : 'C�l karakter k�dol�s',
mime : 'C�l MIME t�pus',
rel : 'Oldal kapcsolata a c�llal',
rev : 'C�l kapcsolat az oldallal',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Balr�l jobbra',
rtl : 'Jobbr�l balra'
});
