// PL lang variables
// fixed by Wooya
// http://www.mfusion.prv.pl
// fixed by lemiel 14.11.2005

tinyMCE.addToLang('advlink',{
general_tab : 'G��wne ustawienia',
popup_tab : 'Okienko popup',
events_tab : 'Zdarzenia',
advanced_tab : 'Zaawansowane',
general_props : 'G��wne',
popup_props : 'Ustawienia popup',
event_props : 'Zdarzenia',
advanced_props : 'Zaawansowane opcje',
popup_opts : 'Opcje',
anchor_names : 'Kotwice',
target_same : 'Otw�rz w tym oknie / ramce',
target_parent : 'Otw�rz w poprzednim oknie / ramce',
target_top : 'Otw�rz w g��wnej ramce (zamienia wszystkie ramki)',
target_blank : 'Otw�rz w nowym oknie',
popup : 'Okienko popup Javascript',
popup_url : 'URL dla popup',
popup_name : 'Nazwa okna',
popup_return : 'Wstaw \'return false\'',
popup_scrollbars : 'Poka� paski przewijania',
popup_statusbar : 'Poka� pasek statusu',
popup_toolbar : 'Poka� pasek narz�dzi',
popup_menubar : 'Poka� pasek menu',
popup_location : 'Poka� pasek adresu',
popup_resizable : 'Pozwalaj na zmian� wielko�ci okna',
popup_dependent : 'Zale�ne (tylko Mozilla/Firefox)',
popup_size : 'Rozmiar',
popup_position : 'Pozycja (X/Y)',
id : 'Id',
style: 'Styl',
classes : 'Klasa',
target_name : 'Nazwa celu',
langdir : 'Kierunek tekstu',
target_langcode : 'J�zyk celu',
langcode : 'Kod j�zyka',
encoding : 'Kodowanie znak�w celu',
mime : 'Typ MIME celu',
rel : 'Zale�no�� strony do celu',
rev : 'Zale�no�� celu do strony',
tabindex : 'Indeks tabeli',
accesskey : 'Klawisz dost�pu',
ltr : 'Lewy do prawego',
rtl : 'Prawy do lewego'
});
