// RU KOI8-R lang variables

tinyMCE.addToLang('advlink',{
general_tab : '��������',
popup_tab : '�����������',
events_tab : '�������',
advanced_tab : '�����������',
general_props : '�������� ��������',
popup_props : '�������� Popup ���������',
event_props : '�������',
advanced_props : '����������� ���������',
popup_opts : '�����',
anchor_names : '�����',
target_same : '��������� � ���� ���� / ������',
target_parent : '��������� � ������������ ���� / ������',
target_top : '��������� � ������� ������ (�������� ��� ������)',
target_blank : '��������� � ����� ����',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : '��� ����',
popup_return : 'Insert \'return false\'',
popup_scrollbars : '���������� ������� ���������',
popup_statusbar : '���������� status bar',
popup_toolbar : '���������� ������ ������������',
popup_menubar : '���������� ������ ����',
popup_location : '���������� location bar',
popup_resizable : '��������� �������� ������� ����',
popup_dependent : '����������� (������ Mozilla/Firefox)',
popup_size : '������',
popup_position : '������������ (X/Y)',
id : 'Id',
style: '�����',
classes : '������',
target_name : '��� ����',
langdir : '����������� ������ � �����',
target_langcode : '������� ����',
langcode : '��� �����',
encoding : '������� ���������',
mime : '������� MIME ���',
rel : '����������� page -> target',
rev : '����������� target -> page',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : '����� �������',
rtl : '������ ������'
});
