// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Genel',
popup_tab : 'Popup',
events_tab : 'Olaylar',
advanced_tab : 'Geli�mi�',
general_props : 'Genel �zellikler',
popup_props : 'Popup �zellikleri',
event_props : 'Olaylar',
advanced_props : 'Geli�mi� �zellikler',
popup_opts : 'Se�enekler',
anchor_names : 'Ba�lant�lar',
target_same : 'Bu pencerede/�er�evede a�',
target_parent : 'Ana pencerede/�er�evede a�',
target_top : '�st �erc�evede a�(b�t�n �er�eveleri de�i�tirir)',
target_blank : 'Yeni pencerede a�',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Pencere ismi',
popup_return : '\'return false\' ekle',
popup_scrollbars : 'Kayd�rma �ubu�unu g�ster',
popup_statusbar : 'Durum �ubu�unu g�ster',
popup_toolbar : 'Ara� �ubuklar�n� g�ster',
popup_menubar : 'Men� �ubu�unu g�ster',
popup_location : 'Adres sat�r�n� g�ster',
popup_resizable : 'Pencereyi yeniden boyutland�r�labilir yap',
popup_dependent : 'Ana pencereye ba��ml� (sadece Mozilla/Firefox)',
popup_size : 'B�y�kl�k',
popup_position : 'Posizyon (X/Y)',
id : 'Id',
style: 'Stil',
classes : 'S�n�flar',
target_name : 'Hedef isim',
langdir : 'Dil y�n�',
target_langcode : 'Hedef dil',
langcode : 'Dil kodu',
encoding : 'Hedef karakter kodlamas�',
mime : 'Hedef MIME tipi',
rel : 'Sayfa - hedef ili�kisi',
rev : 'Hedef - sayfa ili�kisi',
tabindex : 'Tabindeks',
accesskey : 'Eri�im anahtar�',
ltr : 'Soldan sa�a',
rtl : 'Sa�dan sola'
});
