// Simplified Chinese lang variables contributed by tom_cat (thomaswangyang@gmail.com)

tinyMCE.addToLang('advlink',{
general_tab : 'һ��',
popup_tab : '����',
events_tab : '�¼�',
advanced_tab : '�߼�',
general_props : 'һ������',
popup_props : '��������',
event_props : '�¼�����',
advanced_props : '�߼�����',
popup_opts : 'ѡ��',
anchor_names : 'ê��',
target_same : '�ڵ�ǰ����/����д�',
target_parent : '�ڸ�����/����д�',
target_top : '�ڶ��˴���/����д�',
target_blank : '���´����д�',
popup : 'Javascript ����',
popup_url : '������ַ',
popup_name : '����������',
popup_return : '���� \'return false\'',
popup_scrollbars : '��ʾ������',
popup_statusbar : '��ʾ״̬��',
popup_toolbar : '��ʾ������',
popup_menubar : '��ʾ�˵���',
popup_location : '��ʾ��ַ��',
popup_resizable : '���ڴ�С�ɱ�',
popup_dependent : 'Dependent (������ Mozilla/Firefox)',
popup_size : '��С',
popup_position : 'λ�� (X/Y)',
id : '��ʶ',
style: '��ʽ',
classes : '��',
target_name : 'Ŀ�����',
langdir : '��д����',
target_langcode : 'Ŀ������',
langcode : '���Ա���',
encoding : 'Ŀ�����ֱ���',
mime : 'Ŀ�� MIME ����',
rel : 'ҳ��Ŀ��Ĺ�ϵ',
rev : 'Ŀ����ҳ�Ĺ�ϵ',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : '������',
rtl : '���ҵ���'
});
