// Traditional Chinese BIG-5; Twapweb Site translated; twapweb_AT_gmail_DOT_com
// �c�餤�� BIG-5 �F�Ʀ����Χ{�s�@�F twapweb_AT_gmail_DOT_com

tinyMCE.addToLang('advlink',{
general_tab : '�@��',
popup_tab : '���{��',
events_tab : '�ƥ�',
advanced_tab : '�i��',
general_props : '�@���ݩ�',
popup_props : '���{���ݩ�',
event_props : '�ƥ��ݩ�',
advanced_props : '�i���ݩ�',
popup_opts : '�ﶵ',
anchor_names : '�s���I',
target_same : '�󦹵�ήج[���}��',
target_parent : '��W�h��ήج[���}��',
target_top : '��D�ج[���}�ҡ]�|��N�����ج[�^',
target_blank : '��s���}��',
popup : 'Javascript ���{��',
popup_url : '���{����}',
popup_name : '��W��',
popup_return : '���J "�T�^�W��"',
popup_scrollbars : '��ܲ��ʶb',
popup_statusbar : '��ܪ��A�C',
popup_toolbar : '��ܤu��C',
popup_menubar : '��ܿ��C',
popup_location : '��ܦ�m�C',
popup_resizable : '�i�j�p�Ƶ�',
popup_dependent : '�q�ݩʡ]�ȾA�� Mozilla / Firefox �^',
popup_size : '�j�p',
popup_position : '��m�] X / Y �b�^',
id : '�s�X',
style: '����',
classes : '����',
target_name : '��H�W��',
langdir : '�y���Ϊk',
target_langcode : '��H�y��',
langcode : '�y�X',
encoding : '��H�r���s�X',
mime : '��H MIME ����',
rel : '�N�����P��H�������p',
rev : '�N��H�P�����������p',
tabindex : '���ү���',
accesskey : '�s����',
ltr : '�ѥ��ܥk',
rtl : '�ѥk�ܥ�'
});
