// Greek lang variables by Jacaranda Bill

tinyMCE.addToLang('',{
theme_style_select : '������',
theme_code_desc : '&Aring;�&aring;�&aring;������ HTML ��&auml;���',
theme_code_title : '&Aring;�&aring;�&aring;������� HTML',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : '&Auml;&aring;�����',
theme_sup_desc : '&Aring;������',
theme_hr_desc : '&Aring;������� ���������� �������',
theme_removeformat_desc : '������&ouml;� ���&ouml;��������',
theme_custom1_desc : '�&aring;�����&ouml;�',
insert_image_border : '�&aring;��������',
insert_image_dimensions : '&Auml;������&aring;��',
insert_image_vspace : '���. �&aring;�������',
insert_image_hspace : '����. �&aring;�������',
insert_image_align : '��������',
insert_image_align_default : '��������������',
insert_image_align_baseline : '�&aring; &aring;����������� �&aring; �� �&aring;��&aring;��',
insert_image_align_top : '����',
insert_image_align_middle : '��� ������',
insert_image_align_bottom : '����',
insert_image_align_texttop : '�� �&aring;��&aring;�� ����',
insert_image_align_absmiddle : '������� ��� ������',
insert_image_align_absbottom : '������� ����',
insert_image_align_left : '�����&aring;��',
insert_image_align_right : '&Auml;&aring;���',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : '�������&ouml;��',
theme_div : 'Div',
theme_address : '&Auml;�&aring;������',
theme_pre : 'Preformatted',
theme_h1 : '&Aring;���&aring;&ouml;���&auml;� 1',
theme_h2 : '&Aring;���&aring;&ouml;���&auml;� 2',
theme_h3 : '&Aring;���&aring;&ouml;���&auml;� 3',
theme_h4 : '&Aring;���&aring;&ouml;���&auml;� 4',
theme_h5 : '&Aring;���&aring;&ouml;���&auml;� 5',
theme_h6 : '&Aring;���&aring;&ouml;���&auml;� 6',
theme_colorpicker_title : '�������',
theme_colorpicker_apply : '&Aring;&ouml;������',
theme_forecolor_desc : '&Aring;������ �������� ���������&aring;����',
theme_backcolor_desc : 'Select background color',
theme_charmap_title : '&Aring;������ &aring;�&auml;���� ���������',
theme_charmap_desc : '&Aring;������� &aring;�&auml;���� ���������',
theme_visualaid_desc : '&Aring;�&ouml;�����/�������� �������',
insert_anchor_title : '&Aring;�������/&Auml;������� �������',
insert_anchor_name : '�������� �������',
theme_anchor_desc : '&Aring;�������/&Auml;������� �������',
theme_insert_link_titlefield : '������',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
class_name : '�����', 
newdocument : 'Are you sure you want clear all contents?'
});
