// Canadian French lang variables by Virtuelcom
// Modify by Laurent Dran 13-02-2006
// Modifi� par Normand Lamoureux le 2005-11-12

tinyMCE.addToLang('',{
theme_style_select : '-- Style --',
theme_code_desc : 'Afficher le code source',
theme_code_title : '�dititon du code source',
theme_code_wordwrap : 'Retour � la ligne automatique',
theme_sub_desc : 'Indice',
theme_sup_desc : 'Exposant',
theme_hr_desc : 'Ins�rer une r�gle horizontale ordinaire',
theme_removeformat_desc : 'Supprimer le formattage',
theme_custom1_desc : 'Votre description personnalis�e ici',
insert_image_border : 'Bordure',
insert_image_dimensions : 'Dimensions',
insert_image_vspace : 'Espacement vertical',
insert_image_hspace : 'Espacement horizontal',
insert_image_align : 'Alignement',
insert_image_align_default : '-- Ind�fini --',
insert_image_align_baseline : 'Ligne de base',
insert_image_align_top : 'Haut',
insert_image_align_middle : 'Milieu',
insert_image_align_bottom : 'Bas',
insert_image_align_texttop : 'Haut du texte',
insert_image_align_absmiddle : 'Milieu absolu',
insert_image_align_absbottom : 'Bas absolu',
insert_image_align_left : 'En flottement � gauche',
insert_image_align_right : 'En flottement � droite',
theme_font_size : '-- Taille --',
theme_fontdefault : '-- Police --',
theme_block : '-- Bloc de texte --',
theme_paragraph : 'Paragraphe',
theme_div : 'Div',
theme_address : 'Infos sur l\'auteur',
theme_pre : 'Texte pr�format�',
theme_h1 : 'Titre de niveau 1',
theme_h2 : 'Titre de niveau 2',
theme_h3 : 'Titre de niveau 3',
theme_h4 : 'Titre de niveau 4',
theme_h5 : 'Titre de niveau 5',
theme_h6 : 'Titre de niveau 6',
theme_colorpicker_title : 'Choisir une couleur',
theme_colorpicker_apply : 'Appliquer',
theme_forecolor_desc : 'Couleur du texte',
theme_backcolor_desc : 'Couleur d\'arri�re-plan',
theme_charmap_title : 'S�lectionner un charact�re sp�cial',
theme_charmap_desc : 'Ins�rer un charact�re sp�cial',
theme_visualaid_desc : 'Activer/D�sactiver les lignes guides et les �l�ments invisibles',
insert_anchor_title : 'Gestionnaire d\'ancre',
insert_anchor_name : 'Nom de l\'ancre',
theme_anchor_desc : 'Ins�rer/Modifier une ancre',
theme_insert_link_titlefield : 'Info-bulle',
theme_clipboard_msg : 'Pour des raisons de s�curit�, les fonctions � Copier �, � Couper � et � Coller �\nne sont pas disponibles dans Mozilla et Firefox.\n\n\nVoulez-vous plus d\'information � ce sujet?\n',
theme_path : '�l�ment(s) en cours ',
cut_desc : 'Couper',
copy_desc : 'Copier',
paste_desc : 'Coller',
link_list : 'Lien de la liste',
image_list : 'Image de la liste',
browse : 'Naviguer',
image_props_desc : 'Propri�t�s de l\'image',
newdocument_desc : 'Nouveau document',
class_name : 'Classe CSS',
newdocument : '�tes-vous s�r de vouloir supprimer tout le contenu ?',
about_title : '� propos de TinyMCE',
about : '� propos',
license : 'License',
plugins : 'Extensions',
plugin : 'Extension',
author : 'Auteur',
version : 'Version',
loaded_plugins : 'Extensions install�es',
help : 'Aide',
not_set : '-- Ind�fini --',
close : 'Fermer',
toolbar_focus : 'Atteindre la barre d\'outils (Alt+Q), Atteindre l\'�diteur (Alt-Z), Atteindre l\'�l�ment en cours (Alt-X)'
});
