// Canadian French lang variables by Virtuelcom   last modification: 2005-06-15

tinyMCE.addToLang('',{
theme_style_select : '-- Styles --',
theme_code_desc : 'Modifier le code source HTML',
theme_code_title : '�diteur de code source HTML',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'Souscrit',
theme_sup_desc : 'Indice sup�rieur',
theme_hr_desc : 'Ins�rer un s�parateur horizontal',
theme_removeformat_desc : 'Supprimer le formattage',
theme_custom1_desc : 'Votre description personnalis�e ici',
insert_image_border : 'Bordure',
insert_image_dimensions : 'Dimensions',
insert_image_vspace : 'VSpace',
insert_image_hspace : 'HSpace',
insert_image_align : 'Alignement',
insert_image_align_default : 'D�faut',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Haut',
insert_image_align_middle : 'Milieu',
insert_image_align_bottom : 'Bas',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Milieu absolu',
insert_image_align_absbottom : 'Bas absolu',
insert_image_align_left : 'Gauche',
insert_image_align_right : 'Droit',
theme_font_size : 'Taille',
theme_fontdefault : '-- Police --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraphe',
theme_div : 'Div',
theme_address : 'Addresse',
theme_pre : 'Pr�formatt�',
theme_h1 : 'Ent�te 1',
theme_h2 : 'Ent�te 2',
theme_h3 : 'Ent�te 3',
theme_h4 : 'Ent�te 4',
theme_h5 : 'Ent�te 5',
theme_h6 : 'Ent�te 6',
theme_colorpicker_title : 'Choisir une couleur',
theme_colorpicker_apply : 'Appliquer',
theme_forecolor_desc : 'Choisir la couleur d\'avant plan',
theme_backcolor_desc : 'Choisir une couleur d\'arri�re plan',
theme_charmap_title : 'S�lectionner un charact�re sp�cial',
theme_charmap_desc : 'Ins�rer un charact�re sp�cial',
theme_visualaid_desc : 'Active/D�sactive les lignes guides et les �l�ments invisibles',
insert_anchor_title : 'Ins�rer/Modifier une ancre',
insert_anchor_name : 'Nom de l\'ancre',
theme_anchor_desc : 'Ins�rer / Modifier une ancre',
theme_insert_link_titlefield : 'Titre',
theme_clipboard_msg : 'Copier/Couper/Coller ne sont pas disponibles dans Mozilla et FireFox.\nD�sirez-vous consulter de plus amples informations � ce sujet?',
theme_path : 'Chemin',
cut_desc : 'Couper',
copy_desc : 'Copier',
paste_desc : 'Coller',
link_list : 'Liste de liens',
image_list : 'Liste d\'images',
browse : 'S�lectionner',
image_props_desc : 'Propri�t�s de l\'image',
newdocument_desc : 'Nouveau Document',
class_name : 'Classe',
newdocument : 'Are you sure you want clear all contents?'
});
