// HU lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- St�lusok --',
theme_code_desc : 'HTML forr�s szerkeszt�se',
theme_code_title : 'HTML forr�s szerkeszt�',
theme_code_wordwrap : 'Sort�rdel�s',
theme_sub_desc : 'Als�index',
theme_sup_desc : 'Fels�index',
theme_hr_desc : 'Vizsz�ntes vonal besz�r�sa',
theme_removeformat_desc : 'Form�z�s elt�vol�t�sa',
theme_custom1_desc : 'Az egy�ni le�r�sod j�n ide',
insert_image_border : 'Keret',
insert_image_dimensions : 'Kiterjed�s',
insert_image_vspace : 'F�gg�leges ter�let',
insert_image_hspace : 'Vizszintes ter�let',
insert_image_align : 'Elhelyezked�s',
insert_image_align_default : '-- Nincs be�ll�tva --',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Fel�l',
insert_image_align_middle : 'K�z�pen',
insert_image_align_bottom : 'Alul',
insert_image_align_texttop : 'Sz�vegfelett',
insert_image_align_absmiddle : 'Abszol�t k�z�p',
insert_image_align_absbottom : 'Abszol�t alatt',
insert_image_align_left : 'Balra',
insert_image_align_right : 'Jobbra',
theme_font_size : '-- Bet�m�ret --',
theme_fontdefault : '-- Bet�csal�d --',
theme_block : '-- Form�tum --',
theme_paragraph : 'Bekezd�s',
theme_div : 'Div',
theme_address : 'C�m',
theme_pre : 'El�reform�zott',
theme_h1 : 'Fejl�c 1',
theme_h2 : 'Fejl�c 2',
theme_h3 : 'Fejl�c 3',
theme_h4 : 'Fejl�c 4',
theme_h5 : 'Fejl�c 5',
theme_h6 : 'Fejl�c 6',
theme_colorpicker_title : 'Sz�nv�laszt�s',
theme_colorpicker_apply : 'Alkalmaz',
theme_forecolor_desc : 'Sz�vegsz�n v�laszt�s',
theme_backcolor_desc : 'H�tt�rsz�n v�laszt�s',
theme_charmap_title : 'Egy�ni karakter v�laszt�s',
theme_charmap_desc : 'Egy�ni karakter besz�r�s',
theme_visualaid_desc : 'Sorjel�l�k/l�thatatlan elemek kapcsol�sa',
insert_anchor_title : 'Horgony nbeilleszt�se/szerkeszt�se',
insert_anchor_name : 'Horgony n�v',
theme_anchor_desc : 'Horgony nbeilleszt�se/szerkeszt�se',
theme_insert_link_titlefield : 'C�m',
theme_clipboard_msg : 'A M�sol�s/Kiv�g�s/Beilleszt�s nem el�rhet� Mozill�ban and Firefox-ban.\nSzeretn�l t�bb inform�ci�t err�l a probl�m�r�l?',
theme_path : '�tvonal',
cut_desc : 'Kiv�g�s',
copy_desc : 'M�sol�s',
paste_desc : 'Beilleszt�s',
link_list : 'Link lista',
image_list : 'K�p lista',
browse : 'Tall�z�s',
image_props_desc : 'K�p tulajdons�gai',
newdocument_desc : '�j dokumentum',
class_name : 'Oszt�ly',
newdocument : 'Biztos hogy t�r�lni akarod az �sszes tartalmat?',
about_title : 'TinyMCE n�vjegye',
about : 'N�vjegy',
license : 'Licensz',
plugins : 'B�v�tm�nyek',
plugin : 'B�v�tm�ny',
author : 'Szerz�',
version : 'Verzi�',
loaded_plugins : 'Bet�lt�tt b�v�tm�nyek',
help : 'S�g�',
not_set : '-- Nincs be�ll�tva --',
close : 'Bez�r�s'
});
