// KO lang variables

tinyMCE.addToLang('',{
theme_style_select : '��&Aring;���',
theme_code_desc : 'HTML �ҽ� ��&Auml;���',
theme_code_title : 'HTML �ҽ� �����',
theme_code_wordwrap : 'Word wrap',
theme_code_save : '���&aring;',
theme_sub_desc : '�Ʒ�÷��',
theme_sup_desc : '��÷��',
theme_hr_desc : '������ �&Ouml;��',
theme_removeformat_desc : '�Ӽ� �&ouml;���',
theme_custom1_desc : 'Your custom description here',
insert_image_border : '&Aring;׵θ�',
insert_image_dimensions : '&Aring;���',
insert_image_vspace : '���� ����',
insert_image_hspace : '���� ����',
insert_image_align : '���&Auml;',
insert_image_align_default : '�⺻��',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Top',
insert_image_align_middle : 'Middle',
insert_image_align_bottom : 'Bottom',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Absolute Middle',
insert_image_align_absbottom : 'Absolute Bottom',
insert_image_align_left : 'Left',
insert_image_align_right : 'Right',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : '�ܶ�',
theme_div : 'Div',
theme_address : '�&Ouml;��',
theme_pre : '���&Auml; �&Ouml;��',
theme_h1 : '���� 1',
theme_h2 : '���� 2',
theme_h3 : '���� 3',
theme_h4 : '���� 4',
theme_h5 : '���� 5',
theme_h6 : '���� 6',
theme_colorpicker_title : '�&ouml;�� ��&Aring;�',
theme_colorpicker_apply : '���',
theme_forecolor_desc : '���� �&ouml;��',
theme_backcolor_desc : 'Select background color',
theme_charmap_title : 'Select custom character',
theme_charmap_desc : 'Insert custom character',
theme_visualaid_desc : 'Toggle guidelines/invisible elements',
insert_anchor_title : '��&Auml;� �&Ouml;��/��&Auml;���',
insert_anchor_name : '��&Auml;� �̸�',
theme_anchor_desc : '��&Auml;� �&Ouml;��/��&Auml;���',
theme_insert_link_titlefield : '����',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
class_name : '&Aring;�����',
newdocument : 'Are you sure you want clear all contents?'
});
