// PT lang variables

tinyMCE.addToLang('',{
theme_style_select : 'Estilos CSS',
theme_code_desc : 'Editar Fonte HTML',
theme_code_title : 'Editor de fonte HTML',
theme_code_save : 'Guardar',
theme_code_wordwrap : 'Translinear palavras',
theme_sub_desc : 'Subscrito',
theme_sup_desc : 'Superscrito',
theme_hr_desc : 'Inserir linha horizontal',
theme_removeformat_desc : 'Remover formata��o',
theme_custom1_desc : 'Descri��o customizada aqui',
insert_image_border : 'Borda',
insert_image_dimensions : 'Dimens�es',
insert_image_vspace : 'Espa�amento Vert.',
insert_image_hspace : 'Espa�amento Horiz.',
insert_image_align : 'Alinhamento',
insert_image_align_default : 'Por omiss�o',
insert_image_align_baseline : 'Linha de base',
insert_image_align_top : 'Topo',
insert_image_align_middle : 'Centrado',
insert_image_align_bottom : 'Fundo',
insert_image_align_texttop : 'Topo do Texto',
insert_image_align_absmiddle : 'Centrado absoluto',
insert_image_align_absbottom : 'Fundo absoluto',
insert_image_align_left : 'Esquerda',
insert_image_align_right : 'Direita',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : 'Par�grafo',
theme_div : 'Bloco HTML',
theme_address : 'Morada',
theme_pre : 'Pr� formatado',
theme_h1 : 'T�tulo 1',
theme_h2 : 'T�tulo 2',
theme_h3 : 'T�tulo 3',
theme_h4 : 'T�tulo 4',
theme_h5 : 'T�tulo 5',
theme_h6 : 'T�tulo 6',
theme_colorpicker_title : 'Seleccione uma c�r',
theme_colorpicker_apply : 'Aplicar',
theme_forecolor_desc : 'Seleccione c�r da frente',
theme_backcolor_desc : 'Select background color',
theme_charmap_title : 'Seleccione s�mbolo customizado',
theme_charmap_desc : 'Inserir s�mbolo customizado',
theme_visualaid_desc : 'Ligar/Desligar guias/elementos invis�veis',
insert_anchor_title : 'Inserir/editar �ncora',
insert_anchor_name : 'Nome da �ncora',
theme_anchor_desc : 'Inserir/editar �ncora',
theme_insert_link_titlefield : 'T�tulo',
theme_clipboard_msg : 'Copiar/Cortar/Colar n�o est� dispon�vel em Mozilla e Firefox.\nPretende obter mais informa��o acerca deste assunto?',
theme_path : 'Path',
cut_desc : 'Cortar',
copy_desc : 'Copiar',
paste_desc : 'Colar',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
class_name : 'Classe de CSS',
newdocument : 'Are you sure you want clear all contents?'
});
