// Russian lang variables cp1251

tinyMCE.addToLang('',{
theme_style_select : '-- ����� --',
theme_code_desc : '������������� HTML ����',
theme_code_title : '�������� HTML �����',
theme_code_wordwrap : '������� �� ������',
theme_sub_desc : '������ ������',
theme_sup_desc : '������� ������',
theme_hr_desc : '�������� �������������� �����������',
theme_removeformat_desc : '������ ��������������',
theme_custom1_desc : '���� ������������ ��������',
insert_image_border : '�����',
insert_image_dimensions : '�������',
insert_image_vspace : '������������ ������',
insert_image_hspace : '�������������� ������',
insert_image_align : '������������',
insert_image_align_default : '-- �� ������ --',
insert_image_align_baseline : '�� ������� �����',
insert_image_align_top : '�� �����',
insert_image_align_middle : '���������',
insert_image_align_bottom : '�� ����',
insert_image_align_texttop : '�� ����� ������',
insert_image_align_absmiddle : '��������� ���������',
insert_image_align_absbottom : '��������� ������',
insert_image_align_left : '�����',
insert_image_align_right : '������',
theme_font_size : '-- ������ ������ --',
theme_fontdefault : '-- ��������� ������� --',
theme_block : '-- ������ --',
theme_paragraph : '�����',
theme_div : 'Div',
theme_address : '����� ������',
theme_pre : ':`�������������� ���������������',
theme_h1 : '��������� 1',
theme_h2 : '��������� 2',
theme_h3 : '��������� 3',
theme_h4 : '��������� 4',
theme_h5 : '��������� 5',
theme_h6 : '��������� 6',
theme_colorpicker_title : '������� ����',
theme_colorpicker_apply : '���������',
theme_forecolor_desc : '������� ���� ������',
theme_backcolor_desc : '������� ���� ����',
theme_charmap_title : '����� ������������� �������',
theme_charmap_desc : '�������� ������������ ������',
theme_visualaid_desc : '�������� ������� ������� ���������',
insert_anchor_title : '��������/������������� �����',
insert_anchor_name : '��� �����',
theme_anchor_desc : '��������/������������� �����',
theme_insert_link_titlefield : '���������',
theme_clipboard_msg : '����������/��������/�������� ���������� ��� Mozilla � Firefox.\n������ ������ �� ���� ���������?',
theme_path : '����',
cut_desc : '��������',
copy_desc : '����������',
paste_desc : '��������',
link_list : '�������� ������',
image_list : '�������� ��������',
browse : '���������',
image_props_desc : '�������� ��������',
newdocument_desc : '����� ��������',
class_name : '�����',
newdocument : '�� �������, ��� ������ �������� �� ����������?',
about_title : '� TinyMCE',
about : '� TinyMCE',
license : '��������',
plugins : '�������',
plugin : '������',
author : '�����',
version : '������',
loaded_plugins : '����������� �������',
help : '������',
not_set : '-- �� ����������� --',
close : '�������',
toolbar_focus : '����������� ����� �� ������ ������������ - Alt+Q, ����������� ����� � �������� - Alt-Z, ����������� ����� �� ������� ���� - Alt-X'
});
