// UK lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Stiller --',
theme_code_desc : 'HTML Kayna�� D�zenle',
theme_code_title : 'HTML Edit�r�',
theme_code_wordwrap : 'S�zc�k kayd�r',
theme_sub_desc : 'Altsimge',
theme_sup_desc : '�stsimge',
theme_hr_desc : 'Yatay �izgi ekle',
theme_removeformat_desc : 'Format� kald�r',
theme_custom1_desc : '�zel a��klaman�z buraya',
insert_image_border : 'Kenar kal�nl���',
insert_image_dimensions : 'Boyutlar',
insert_image_vspace : 'Dikey bo�luk',
insert_image_hspace : 'Yatay bo�luk',
insert_image_align : 'Hizalama',
insert_image_align_default : '-- Atanmam�� --',
insert_image_align_baseline : 'Taban �izgisi',
insert_image_align_top : '�st',
insert_image_align_middle : 'Orta',
insert_image_align_bottom : 'Alt',
insert_image_align_texttop : 'Yaz� �stte',
insert_image_align_absmiddle : 'Tam ortada',
insert_image_align_absbottom : 'En altta',
insert_image_align_left : 'Sol',
insert_image_align_right : 'Sa�',
theme_font_size : '-- Yaz� boyutu --',
theme_fontdefault : '-- Yaz� tipi --',
theme_block : '-- Bi�im --',
theme_paragraph : 'Paragraf',
theme_div : 'Div etiketi',
theme_address : 'Adres',
theme_pre : '�nceden d�zenlenmi�',
theme_h1 : 'Ba�l�k 1',
theme_h2 : 'Ba�l�k 2',
theme_h3 : 'Ba�l�k 3',
theme_h4 : 'Ba�l�k 4',
theme_h5 : 'Ba�l�k 5',
theme_h6 : 'Ba�l�k 6',
theme_colorpicker_title : 'Renk se�iniz',
theme_colorpicker_apply : 'Uygula',
theme_forecolor_desc : 'Yaz� rengi',
theme_backcolor_desc : 'Arkaplan rengi',
theme_charmap_title : '�zel karakterler',
theme_charmap_desc : '�zel karakter ekle',
theme_visualaid_desc : 'Gizli nesneler',
insert_anchor_title : 'Link ekle/d�zenle',
insert_anchor_name : 'Link ismi',
theme_anchor_desc : 'Link ekle/d�zenle',
theme_insert_link_titlefield : 'Ba�l�k',
theme_clipboard_msg : 'Mozilla ve Firefox taray�c�lar�nda kopyala/kes/yap��t�r komutlar�n� kullanamass�n�z.\n Bu konu hakk�nda daha fazla bilgi edinmek ister misiniz?',
theme_path : 'Etiket yolu',
cut_desc : 'Kes',
copy_desc : 'Kopyala',
paste_desc : 'Yap��t�r',
link_list : 'Link listesi',
image_list : 'Resim listesi',
browse : 'G�zat',
image_props_desc : 'Resim �zellikleri',
newdocument_desc : 'Yeni d�k�man',
class_name : 'S�n�f',
newdocument : 'T�m i�eri�i silmek istedi�inizden emin misiniz?',
about_title : 'TinyMCE Hakk�nda',
about : 'Hakk�nda',
license : 'Lisans',
plugins : 'Pluginler',
plugin : 'Plugin',
author : 'Yazar',
version : 'Versiyon',
loaded_plugins : 'Y�klenen pluginler',
help : 'Yard�m',
not_set : '-- Atanmam�� --',
close : 'Kapat',
toolbar_focus : 'Ara� butonlar�na ge� - Alt+Q , Edit�re ge� - Alt-Z, Eleman �zelliklerine ge� - Alt-X'
});
