// TW lang variables contributed by Jim Kou

tinyMCE.addToLang('',{
bold_desc : '��&Aring;�',
bold_img : "bold.gif",
bullist_desc : '�&Aring;������',
cancel : '���',
cleanup_desc : '�M��',
help_desc : '���U����',
image_desc : '�Ϥ�',
indent_desc : '�Y��',
insert : '�s�W',
insert_anchor_name : '�е�W��',
insert_anchor_title : '�s�W�е�',
insert_image_align : '���',
insert_image_align_absbottom : '�j����U',
insert_image_align_absmiddle : '�j��m��',
insert_image_align_baseline : '��ǽu',
insert_image_align_bottom : '���U',
insert_image_align_default : '�з�',
insert_image_align_left : '����',
insert_image_align_middle : '�m��',
insert_image_align_right : '���k',
insert_image_align_texttop : '�&aring;�r�W��',
insert_image_align_top : '���W',
insert_image_alt : '�Ϥ��',
insert_image_border : '�~��',
insert_image_dimensions : '�ؤo',
insert_image_hspace : '��������',
insert_image_src : '�Ϥ�ӷ�',
insert_image_title : '�s�W�Ϥ�',
insert_image_vspace : '��������',
insert_link_target : '�ؼ�',
insert_link_target_blank : '&Aring;�ܩ�s��',
insert_link_target_same : '&Aring;�ܩ�P�@��',
insert_link_title : '�s�W�W�s��',
insert_link_url : '�W�s��',
italic_desc : '��&Aring;�',
italic_img : "italic.gif",
justifycenter_desc : '����',
justifyfull_desc : '��',
justifyleft_desc : '����',
justifyright_desc : '���k',
link_desc : '�إ߳s��',
numlist_desc : '�Ʀr����',
outdent_desc : '�Y��',
redo_desc : '����',
striketrough_desc : '�R���u',
theme_address : '�a�}',
theme_anchor_desc : '�е�',
theme_charmap_desc : '�S��r��',
theme_charmap_title : '�S��r���M��',
theme_code_desc : '&Aring;�� HTML ��l�X',
theme_code_wordwrap : 'Word wrap',
theme_code_title : 'HTML ��l�X',
theme_colorpicker_apply : '&Aring;ܧ�',
theme_colorpicker_title : '�C��',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_forecolor_desc : '�r���C��',
theme_backcolor_desc : 'Select background color',
theme_h1 : '���D1',
theme_h2 : '���D2',
theme_h3 : '���D3',
theme_h4 : '���D4',
theme_h5 : '���D5',
theme_h6 : '���D6',
theme_hr_desc : '�s�W��u',
theme_paragraph : '�q��',
theme_pre : '���w�榡',
theme_removeformat_desc : '�M���榡�]�w',
theme_style_select : '�˦�',
theme_sub_desc : '�U��',
theme_sup_desc : '�W��',
theme_visualaid_desc : '&Aring;��/���ëD�i��������',
underline_desc : '���u',
undo_desc : '�_��',
unlink_desc : '���s��',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
newdocument : 'Are you sure you want clear all contents?'
});
