// Simplified Chinese lang variables contributed by tom_cat (thomaswangyang@gmail.com)

tinyMCE.addToLang('',{
theme_style_select : '-- ��ʽ --',
theme_code_desc : '�༭HTMLԴ����',
theme_code_title : 'HTMLԴ����༭��',
theme_code_wordwrap : '�Զ�����',
theme_sub_desc : '�±�',
theme_sup_desc : '�ϱ�',
theme_hr_desc : '����ˮƽ��',
theme_removeformat_desc : '�Ƴ��ʽ',
theme_custom1_desc : '������д�û��Զ�������',
insert_image_border : '�߿�',
insert_image_dimensions : 'ά��',
insert_image_vspace : '��ֱ���',
insert_image_hspace : 'ˮƽ���',
insert_image_align : '���뷽ʽ',
insert_image_align_default : '-- Ĭ�� --',
insert_image_align_baseline : '����',
insert_image_align_top : '����',
insert_image_align_middle : '����',
insert_image_align_bottom : '�ײ�',
insert_image_align_texttop : '�����Ϸ�',
insert_image_align_absmiddle : '��Ծ���',
insert_image_align_absbottom : '��Եײ�',
insert_image_align_left : '�����',
insert_image_align_right : '�Ҷ���',
theme_font_size : '-- �ֺ� --',
theme_fontdefault : '-- ���� --',
theme_block : '-- ��ʽ --',
theme_paragraph : '����',
theme_div : '��',
theme_address : '��ַ',
theme_pre : 'Ԥ��ʽ��',
theme_h1 : '���� 1',
theme_h2 : '���� 2',
theme_h3 : '���� 3',
theme_h4 : '���� 4',
theme_h5 : '���� 5',
theme_h6 : '���� 6',
theme_colorpicker_title : 'ѡ����ɫ',
theme_colorpicker_apply : 'Ӧ��',
theme_forecolor_desc : 'ѡ��������ɫ',
theme_backcolor_desc : 'ѡ�񱳾���ɫ',
theme_charmap_title : 'ѡ��������',
theme_charmap_desc : '����������',
theme_visualaid_desc : '���ز��ɼ�Ԫ��',
insert_anchor_title : '����/�༭ ê��',
insert_anchor_name : 'ê�����',
theme_anchor_desc : '����/�༭ ê��',
theme_insert_link_titlefield : '����',
theme_clipboard_msg : '����/����/ճ������ Mozilla �� Firefox ������в�֧�֡�\n��ϣ���ø�����Ϣ��',
theme_path : '·��',
cut_desc : '����',
copy_desc : '����',
paste_desc : 'ճ��',
link_list : '�����б�',
image_list : 'ͼ���б�',
browse : '���',
image_props_desc : 'ͼ������',
newdocument_desc : '�½��䵵',
class_name : '��',
newdocument : '��ȷ��Ҫ�������������',
about_title : '���� TinyMCE',
about : '����',
license : '��Ȩ��',
plugins : '���в��',
plugin : '���',
author : '����',
version : '�汾',
loaded_plugins : '��ȡ���',
help : '����',
not_set : '-- ���趨 --',
close : '�ر�',
toolbar_focus : '���߰�ť - Alt+Q, ��༭�� - Alt-Z, ��Ԫ��·�� - Alt-X'
});
