// Traditional Chinese BIG-5; Twapweb Site translated; twapweb_AT_gmail_DOT_com
// �c�餤�� BIG-5 �F�Ʀ����Χ{�s�@�F twapweb_AT_gmail_DOT_com


tinyMCE.addToLang('',{
theme_style_select : '-- ���� --',
theme_code_desc : '�s�� HTML �X',
theme_code_title : 'HTML �X�s�边',
theme_code_wordwrap : '�r����¶',
theme_sub_desc : '�U��',
theme_sup_desc : '�W��',
theme_hr_desc : '���J�����u',
theme_removeformat_desc : '�M���榡�]�w',
theme_custom1_desc : '�ۭq����b����J',
insert_image_border : '�ؽu',
insert_image_dimensions : '�ؤo',
insert_image_vspace : '�Ϲ��W�U�����Z',
insert_image_hspace : '�Ϲ����k�䶡�Z',
insert_image_align : '�������',
insert_image_align_default : '-- ���]�m --',
insert_image_align_baseline : '���u',
insert_image_align_top : '����',
insert_image_align_middle : '���u',
insert_image_align_bottom : '����',
insert_image_align_texttop : '��r����',
insert_image_align_absmiddle : '���襤�u',
insert_image_align_absbottom : '���侀��',
insert_image_align_left : '��',
insert_image_align_right : '�k',
theme_font_size : '-- �r��j�p --',
theme_fontdefault : '-- �r���� --',
theme_block : '-- �榡 --',
theme_paragraph : '�q��',
theme_div : '����',
theme_address : '��m',
theme_pre : '���w�榡',
theme_h1 : '���D�@',
theme_h2 : '���D�G',
theme_h3 : '���D�T',
theme_h4 : '���D�|',
theme_h5 : '���D��',
theme_h6 : '���D��',
theme_colorpicker_title : '����C��',
theme_colorpicker_apply : '�M��',
theme_forecolor_desc : '����r�C��',
theme_backcolor_desc : '���I���C��',
theme_charmap_title : '���ۭq�r��',
theme_charmap_desc : '���J�ۭq�r��',
theme_visualaid_desc : '������ܩΫD�i������',
insert_anchor_title : '���J�νs��s���I',
insert_anchor_name : '�s���I�W��',
theme_anchor_desc : '���J�νs��s���I',
theme_insert_link_titlefield : '���D',
theme_clipboard_msg : '�b Mozilla �M Firefox ���L�k�ϥνƻs�ΰŤU�ζK�W�\��C\n�ݭn��h���󦹪��T���ܡH',
theme_path : '���|',
cut_desc : '�ŤU',
copy_desc : '�ƻs',
paste_desc : '�K�W',
link_list : '�s���C��',
image_list : '���ɦC��',
browse : '�s��',
image_props_desc : '�����ݩ�',
newdocument_desc : '�s���',
class_name : '����',
newdocument : '�T�w�n�M���������e�H',
about_title : '���� TinyMCE',
about : '����',
license : '���v',
plugins : '���ήM��',
plugin : '���ήM��',
author : '�@��',
version : '����',
loaded_plugins : '�w��J���ήM��',
help : '��U',
not_set : '-- ���]�m --',
close : '����',
toolbar_focus : '�ֳt�ҥΤu��� - Alt+Q�F�ֳt�ҥνs�边 - Alt-Z�F�ֳt���ܤ�����| - Alt-X'
});
